### ISSUE TITLE
v4用户

### ISSUE THREAD

**Issue by yangzhicong** [Zy143L/wskey#10]
大佬提供一下对v4的支持阿，v4用户很多

**Comment by Zy143L** [comment]
有v4的API文档吗?

**Comment by sofs2005** [comment]
同求v4，v4没有api，全部都是shell脚本

**Comment by Zy143L** [comment]
v4

> 同求v4，v4没有api，全部都是shell脚本

V4在web操作的时候 应该有js交互吧

**Comment by yangzhicong** [comment]
我有v4 的docker镜像可以吗

**Comment by sofs2005** [comment]
> v4
> 
> > 同求v4，v4没有api，全部都是shell脚本
> 
> V4在web操作的时候 应该有js交互吧

v4原版的web被去掉了，现在都是用的外挂web，我把api那段抠出来：

app.post('/updateCookie', function (request, response) {
    if (request.body.cookie) {
        const cookie = request.body.cookie;
        const userMsg = request.body.userMsg; //备注
        const cookieTime = request.body.cookieTime;
        if (!cookieTime) cookieTime = new Date().getTime() + new Date().getTimezoneOffset() * 60 * 1000 + 8 * 60 * 60 * 1000;
        const content = getFileContentByName(confFile);
        const lines = content.split('\n');
        const pt_pin = cookie.match(/pt_pin=.+?;/)[0];
        const cookieExpireTime = cookieTime + 60 * 60 * 1000 * 24 * 25;//cookie过期的时间戳(这里以25天计算)
        let updateFlag = false;
        let lastIndex = 0;
        let maxCookieCount = 0;
        let umsg = `${userMsg ? ' #用户备注：' + userMsg + ' 过期时间(25天)：' + new Date(cookieExpireTime).toLocaleDateString() : ' #过期时间(25天)：' + new Date(cookieExpireTime).toLocaleDateString()}`;
        let CK_AUTO_ADD = true
        if (content.match(/CK_AUTO_ADD=".+?"/)){CK_AUTO_ADD = content.match(/CK_AUTO_ADD=".+?"/)[0].split('"')[1]}
        for (var i = 0; i < lines.length; i++) {
            var line = lines[i];
            if (line.startsWith('Cookie')) {
                maxCookieCount = Math.max(
                    Number(line.split('=')[0].split('Cookie')[1]),
                    maxCookieCount
                );
                lastIndex = i;
                if (
                    line.match(/pt_pin=.+?;/) &&
                    line.match(/pt_pin=.+?;/)[0] == pt_pin
                ) {
                    const head = line.split('=')[0];
                    //const newLine = [head, '=', '"', cookie, '"', '  ##', userMsg].join
                    const newLine = [head, '=', '"', cookie, '"'].join(
                        ''
                    );
                    lines[i] = newLine;
                    updateFlag = true;
	                var lineNext = lines[i+1];
	                if (
	                    lineNext.match(/上次更新：/)
		                ) {
		                    const acc = lineNext.split('账号：')[1];
		                	const newLine = ['## ', pt_pin, ' 上次更新：', new Date().toLocaleDateString(), umsg, ' 账号：', acc].join('');
                    		lines[i+1] = newLine;
	                	} else {
		                	const newLine = ['## ', pt_pin, ' 上次更新：', new Date().toLocaleDateString(), umsg, ' 账号：'].join('');
			            	lines.splice(lastIndex + 1, 0, newLine);
			        }
                }
            }
        }
        let CookieCount = Number(maxCookieCount) + 1;
        if (!updateFlag && CK_AUTO_ADD === 'true') {
            let newLine = [
                'Cookie',
                CookieCount,
                '=',
                '"',
                cookie,
                '"',
                //'  #',
                //userMsg,
            ].join('');
            //提交备注
            lines.splice(lastIndex + 2, 0, newLine);
            newLine = ['## ', pt_pin, ' 上次更新：', new Date().toLocaleDateString(), umsg, ' 账号：TBD'].join('');
            lines.splice(lastIndex + 3, 0, newLine);
        }
        saveNewConf('config.sh', lines.join('\n'));
        response.send({
            err: 0,
            msg: updateFlag ?
                `[更新成功]\n当前用户量:(${maxCookieCount})` : CK_AUTO_ADD === 'true' ? `[新的Cookie]\n当前用户量:(${CookieCount})` : `服务器配置不自动添加Cookie\n如需启用请添加export CK_AUTO_ADD="true"`,
                //`[更新成功]\n本服用户量:(${maxCookieCount})` : `非本服用户\n本服用户量:(${CookieCount})`,
        });
    } else {
        response.send({
            msg: '参数错误',
            err: -1
        });
    }
});

**Comment by sxx1314** [comment]
> v4
> 
> > 同求v4，v4没有api，全部都是shell脚本
> 
> V4在web操作的时候 应该有js交互吧

 v4 直接修改替换  /jd/config/config.sh 即可。
jd_cookie 变量填写格式为
```
Cookie1=“pt_key=xxxxxx;pt_pin=xxxx”
Cookie2=“pt_key=xxxxxx;pt_pin=xxxx”
Cookie3=“pt_key=xxxxxx;pt_pin=xxxx”
Cookie4=“pt_key=xxxxxx;pt_pin=xxxx”
```

所以只需要把wskey也写入 config.sh
格式可以类似于
```
wskey1=
wskey2=
```

**Comment by sofs2005** [comment]
v4望眼欲穿
