### ISSUE TITLE
未知错误，退出脚本

### ISSUE THREAD

**Issue by le2yun** [Zy143L/wskey#100]
5700端口检查通过
HTTPConnectionPool(host-
*moe. shizuku. ml
port=8443) : Max
retries exceeded with ur: /check api *Caused by
NewConnectionError(
*<urllib3. connection.HTTPConnection
object at 0x7fc92a2939a0>: Failed to establish a new
connection:
[Errno -3] Try again

))
未知错误，退出脚车
请问这是怎么回事呀

**Comment by licky008** [comment]
腾讯云就没事，甲骨文的出错了

**Comment by blucewyan** [comment]
也是报这个错  地址难道要直连？

**Comment by le2yun** [comment]
是的 我就是甲骨文

**Comment by le2yun** [comment]
> 腾讯云就没事，甲骨文的出错了

有什么办法吗

**Comment by licky008** [comment]
不知道，我也不太会，你研究好，发个教程，谢谢

**Comment by le2yun** [comment]
> 不知道，我也不太会，你研究好，发个教程，谢谢

不知道大佬会不会更新😂

**Comment by Zy143L** [comment]
稍等在排查

**Comment by le2yun** [comment]
> 稍等在排查

大佬辛苦了

**Comment by Zy143L** [comment]
请更新脚本

**Comment by le2yun** [comment]
5700端口检查通过

HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd614c0>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误云端, 重试脚本!
HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd61400>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误云端, 重试脚本!
HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd610d0>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误云端, 重试脚本!
企业微信应用 推送打开
Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 423, in <module>
    update()
  File "Zy143L_wskey_wskey.py", line 270, in update
    up_ver = int(cloud_arg['update'])
TypeError: 'NoneType' object is not subscriptable

## 执行结束... 2021-11-01 16:40:33 耗时 22 秒

**Comment by Zy143L** [comment]
> 5700端口检查通过
> 
> HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd614c0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd61400>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd610d0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! 企业微信应用 推送打开 Traceback (most recent call last): File "Zy143L_wskey_wskey.py", line 423, in update() File "Zy143L_wskey_wskey.py", line 270, in update up_ver = int(cloud_arg['update']) TypeError: 'NoneType' object is not subscriptable
> 
> ## 执行结束... 2021-11-01 16:40:33 耗时 22 秒

好的我看到了我检查下 是每次执行都会出现这个错误吗?

**Comment by le2yun** [comment]
> > 5700端口检查通过
> > HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd614c0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd61400>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd610d0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! 企业微信应用 推送打开 Traceback (most recent call last): File "Zy143L_wskey_wskey.py", line 423, in update() File "Zy143L_wskey_wskey.py", line 270, in update up_ver = int(cloud_arg['update']) TypeError: 'NoneType' object is not subscriptable
> > ## 执行结束... 2021-11-01 16:40:33 耗时 22 秒
> 
> 好的我看到了我检查下 是每次执行都会出现这个错误吗?

就是今天更新后出现了原贴的错误 刚才更新后就出现了以上

**Comment by Zy143L** [comment]
> > > 5700端口检查通过
> > > HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd614c0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd61400>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd610d0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! 企业微信应用 推送打开 Traceback (most recent call last): File "Zy143L_wskey_wskey.py", line 423, in update() File "Zy143L_wskey_wskey.py", line 270, in update up_ver = int(cloud_arg['update']) TypeError: 'NoneType' object is not subscriptable
> > > ## 执行结束... 2021-11-01 16:40:33 耗时 22 秒
> > 
> > 
> > 好的我看到了我检查下 是每次执行都会出现这个错误吗?
> 
> 就是今天更新后出现了原贴的错误 刚才更新后就出现了以上

再更新下吧 ver=1103

**Comment by Zy143L** [comment]
还有个问题就是...这个问题我本地无法复现..

**Comment by le2yun** [comment]
5700端口检查通过

HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd21e3cffd0>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误云端, 退出脚本!


> > > > 5700端口检查通过
> > > > HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd614c0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd61400>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd610d0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! 企业微信应用 推送打开 Traceback (most recent call last): File "Zy143L_wskey_wskey.py", line 423, in update() File "Zy143L_wskey_wskey.py", line 270, in update up_ver = int(cloud_arg['update']) TypeError: 'NoneType' object is not subscriptable
> > > > ## 执行结束... 2021-11-01 16:40:33 耗时 22 秒
> > > 
> > > 
> > > 好的我看到了我检查下 是每次执行都会出现这个错误吗?
> > 
> > 
> > 就是今天更新后出现了原贴的错误 刚才更新后就出现了以上
> 
> 再更新下吧 ver=1103

5700端口检查通过

HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd21e3cffd0>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误云端, 退出脚本!

**Comment by Zy143L** [comment]
> 5700端口检查通过
> 
> HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd21e3cffd0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 退出脚本!
> 
> > > > > 5700端口检查通过
> > > > > HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd614c0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd61400>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c0fd610d0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 重试脚本! 企业微信应用 推送打开 Traceback (most recent call last): File "Zy143L_wskey_wskey.py", line 423, in update() File "Zy143L_wskey_wskey.py", line 270, in update up_ver = int(cloud_arg['update']) TypeError: 'NoneType' object is not subscriptable
> > > > > ## 执行结束... 2021-11-01 16:40:33 耗时 22 秒
> > > > 
> > > > 
> > > > 好的我看到了我检查下 是每次执行都会出现这个错误吗?
> > > 
> > > 
> > > 就是今天更新后出现了原贴的错误 刚才更新后就出现了以上
> > 
> > 
> > 再更新下吧 ver=1103
> 
> 5700端口检查通过
> 
> HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd21e3cffd0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 退出脚本!

多执行几次尝试下 ..我这边一直没法复现 挺迷的 nginx那边也没抛出啥错误

**Comment by rjgaoyuan** [comment]
5700端口检查通过

HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa164797df0>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误云端, 退出脚本!

## 执行结束... 2021-11-01 17:15:57 耗时 2 秒

**Comment by rjgaoyuan** [comment]
更新完最新版报错，麻烦大佬有时间能帮忙检查下什么原因，非常感谢！

**Comment by Zy143L** [comment]
> 5700端口检查通过
> 
> HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa164797df0>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误云端, 退出脚本!
> 
> ## 执行结束... 2021-11-01 17:15:57 耗时 2 秒

头疼 稍等1分钟

**Comment by Zy143L** [comment]
从新调整了下服务器 你再试试看

**Comment by rjgaoyuan** [comment]
> 从新调整了下服务器 你再试试看

还是这个报错。。是代码还没提交吗

**Comment by Zy143L** [comment]
> > 从新调整了下服务器 你再试试看
> 
> 还是这个报错。。是代码还没提交吗

我找了三四个人都跑了下..都没问题 建议你那边重启下?

**Comment by Zy143L** [comment]
> > 从新调整了下服务器 你再试试看
> 
> 还是这个报错。。是代码还没提交吗

试了么?>

**Comment by blucewyan** [comment]
重启了还是一样的问题

**Comment by Zy143L** [comment]
我这边找了几个朋友测都没问题...你这要不改下dns

**Comment by Zy143L** [comment]
要不 加我tg
https://t.me/Shizuku_moe

**Comment by licky008** [comment]
一样，重启后，还是同样的错误

**Comment by Zy143L** [comment]
> 一样，重启后，还是同样的错误

加我tg

**Comment by Zy143L** [comment]
请使用甲骨文 等境外服务器的 检查自己的服务器DNS是否为 8.8.8.8 如不是 请更改
国内服务器请使用 119.29.29.29 114.114.114.114

**Comment by onlycup** [comment]
甲骨文云如果使用centos做系统的
修改对应网卡的DNS的配置文件
# vi /etc/resolv.conf 
修改以下内容

nameserver 8.8.8.8 #google域名服务器
nameserver 8.8.4.4 #google域名服务器

然后重启docker应该就可以了

**Comment by le2yun** [comment]
> 甲骨文云如果使用centos做系统的 修改对应网卡的DNS的配置文件
> 
> # vi /etc/resolv.conf
> 修改以下内容
> 
> nameserver 8.8.8.8 #google域名服务器 nameserver 8.8.4.4 #google域名服务器
> 
> 然后重启docker应该就可以了

换了可以用了 感谢
