### ISSUE TITLE
前几天还正常的，莫名其妙报错 求解决

### ISSUE THREAD

**Issue by woodymew** [Zy143L/wskey#102]
5700端口检查通过

HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f02d81ef0d0>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误云端, 退出脚本!

**Comment by Zy143L** [comment]
修改下容器的DNS 是解析的问题

**Comment by Zy143L** [comment]
更新脚本就可以了
