### ISSUE TITLE
WsKey状态失效

### ISSUE THREAD

**Issue by pengneal** [Zy143L/wskey#103]
wskey是在请求sh.jd.com cookie里面找的。
还是提升wskey状态失效.
调试了下，在用wskey请求的时候，发现返回cookie里面是fake开头。

**Comment by pengneal** [comment]
是我找wskey的时候错了吗?我搜索wskey只搜索到一个。。。。

**Comment by Zy143L** [comment]
api.m.jd.com

**Comment by Zy143L** [comment]
> 大佬，可有能快速获取ck和wskey 的方式？ 每次都需要手动抓包。

无

**Comment by ihuanran** [comment]
是在api.m.jd.com域名下抓的wskey，获取还是fake开头的

**Comment by a4081675** [comment]
我的也是这样。从上周五开始的
