### ISSUE TITLE
脚本显示“Telegram 推送打开“，但实际没有推送

### ISSUE THREAD

**Issue by lxr760** [Zy143L/wskey#105]
转换完ck后，脚本日志里最后有“Telegram 推送打开”字样，但实际没有推送信息

已在config和qinglong面板的系统设置里都设置了tg推送

其他脚本执行、登陆青龙面板，tg都能正常收到推送

**Comment by Zy143L** [comment]
这个脚本 除非是出现失效和版本更新才会推送 其他情况下不会推送
Tg推送打开是青龙面板的推送功能的提示而已 提示你有什么推送通道和有没有推送没关

**Comment by lxr760** [comment]
> 这个脚本 除非是出现失效和版本更新才会推送 其他情况下不会推送 Tg推送打开是青龙面板的推送功能的提示而已 提示你有什么推送通道和有没有推送没关


这是我今天早上执行的日志

## 开始执行... 2021-11-03 03:15:22


--------------------

5700端口检查通过

Token失效, 新登陆

青龙登录失败, 请检查面板状态!
Telegram 推送打开

## 更新任务状态失败()


## 执行结束... 2021-11-03 03:35:57 耗时 1235 秒


当时显示token失效     cookie没有更新成功    那么  这种情况应该推送给我  告诉我失败 对吧    实际我却没有收到通知，这样ck到后面就会失效了

**Comment by Zy143L** [comment]
行这个会加入推送. 然后你青龙登录失败 是加了两步验证还是什么呢?

**Comment by Zy143L** [comment]
已经加好了

**Comment by lxr760** [comment]
> 行这个会加入推送. 然后你青龙登录失败 是加了两步验证还是什么呢?

没开2步验证         最近wsk转换经常报错      不稳定

**Comment by Zy143L** [comment]
> > 行这个会加入推送. 然后你青龙登录失败 是加了两步验证还是什么呢?
> 
> 没开2步验证 最近wsk转换经常报错 不稳定

这两天改了很多后端的 现在已经基本OK了
现在更多的问题是某东接口403的问题

**Comment by lxr760** [comment]
> > > 行这个会加入推送. 然后你青龙登录失败 是加了两步验证还是什么呢?
> > 
> > 
> > 没开2步验证 最近wsk转换经常报错 不稳定
> 
> 这两天改了很多后端的 现在已经基本OK了 现在更多的问题是某东接口403的问题

大佬，我看你昨天更新过代码了。请问如果遇到各种原因，导致wsk转换ck失败，现在是不是就有推送通知了？

**Comment by Zy143L** [comment]
对
