### ISSUE TITLE
大佬你好，这个转换出来的ck，经常过期2小时都很难坚持

### ISSUE THREAD

**Issue by prcxu** [Zy143L/wskey#106]

**Comment by Zy143L** [comment]
你是不是开了QL_WSCK变量呢

**Comment by prcxu** [comment]
> 你是不是开了QL_WSCK变量呢

![image](https://user-images.githubusercontent.com/53996229/140041967-256bd3c3-329a-416b-897f-bfb5e0b5733f.png)

**Comment by prcxu** [comment]
![image](https://user-images.githubusercontent.com/53996229/140042231-d965cad6-3179-4585-8bae-eadf997f5efd.png)
大佬 我看了下 py是读取env环境的,正常可以转换,但是没看懂咱们py用的sign是不是固定的

**Comment by Zy143L** [comment]
麻烦审题..QL_WSCK

**Comment by prcxu** [comment]
> 麻烦审题..QL_WSCK

大佬 我的env环境不存在QL_WSCK 这个名字的变量

**Comment by Zy143L** [comment]
那就考虑你那边的号风控问题了..我这边大概24H是没问题的

**Comment by le2yun** [comment]
我最近也是

**Comment by johnleuang** [comment]
一样也是..好奇怪...检查了也没用QL_WSCK

**Comment by le2yun** [comment]
而且最近时不时的转换不成功 一个容器可以 一个容器不行
