### ISSUE TITLE
运行报错，不知道是什么原因

### ISSUE THREAD

**Issue by GuessMine** [Zy143L/wskey#107]
5700端口检查通过

获取云端参数超时, 正在重试!0

获取云端参数超时, 正在重试!1

获取云端参数超时, 正在重试!2
Server酱 推送打开
Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 433, in <module>
    update()
  File "Zy143L_wskey_wskey.py", line 278, in update
    up_ver = int(cloud_arg['update'])
TypeError: 'NoneType' object is not subscriptable

## 执行结束... 2021-11-05 15:07:24 耗时 61 秒

**Comment by Zy143L** [comment]
更新下脚本 可能网络波动

**Comment by GuessMine** [comment]
更新了，还是不行，更新请求的域名是哪个？

**Comment by Zy143L** [comment]
> 更新了，还是不行，更新请求的域名是哪个？

已经是ip直连了...

**Comment by GuessMine** [comment]
那就很奇怪了，还是不行> > 更新了，还是不行，更新请求的域名是哪个？
> 
> 
> 
> 已经是ip直连了...
