### ISSUE TITLE
脚本更新后，容易在部分cookie有效的情况下，出现“JD接口错误码: 401”的报错，导致不断用wskey转换cookie

### ISSUE THREAD

**Issue by Wake2020** [Zy143L/wskey#110]
这个问题，有时是几个账号出现上述报错，有时是全部账号都报错，而一报错，脚本就不会识别cookie是否有效，而直接启动wskey转换。这导致部分账号cookie明明还在有效期内，却因这个报错，不断启用wskey转换。

手动运行与利用cookie失效自动运行该脚本均有一定几率出现上述报错。

不知其他人是否会出现上述情况，但我是脚本更新后才出现的该问题。

**Comment by Zy143L** [comment]
这个问题我有考虑到..是在校验账号有效性的时候 接口返回403错误或者timeout这种情况呢
默认账号失效 如果不想这样子 修改代码 163行  return False 改成   return True

**Comment by Wake2020** [comment]
好的，谢谢大佬，报错频次最近有点高，那我还是修改下。

**Comment by Zy143L** [comment]
建议每天重启网络更换ip
