### ISSUE TITLE
WsKey状态失效

### ISSUE THREAD

**Issue by a4081675** [Zy143L/wskey#118]
是在api.m.jd.com域名下抓的wskey，获取是fake开头的.
![image](https://user-images.githubusercontent.com/17973196/144803787-f0366a2c-95c3-4a6f-b744-efcd103617f8.png)

**Comment by Zy143L** [comment]
退出从新登录 从新抓 一定要主app 不是其他的

**Comment by a4081675** [comment]
@Zy143L 退出重新登陆，然后在京东APP上重新抓的wskey也是这样的

**Comment by a4081675** [comment]
我知道啥原因了。 因为获取不到pin，随便写了个pin导致的。去别的地方弄到pin就正常了

**Comment by Zy143L** [comment]
...谁让你随便写的

**Comment by a4081675** [comment]
哈哈   抱歉      以为这个值只是做匹配用的
