### ISSUE TITLE
ck转换建议增加显示wsck账号几

### ISSUE THREAD

**Issue by LJMX996** [Zy143L/wskey#121]
有时候WSCK转换接口出错，会断掉，不知道在哪个账号断掉，重新转换就会从头开始，多次转换怕会减少有效期，或者建议wsck转换接口出错时候不退出脚本，跳过那个账号，或者脚本停2分钟继续运行

**Comment by Zy143L** [comment]
不使用QL_WSCK变量转换的ck 会先检查有效性的 无需担心多次转换的问题
