### ISSUE TITLE
青龙更新至2.10.12后wskey无法使用

### ISSUE THREAD

**Issue by ryan016** [Zy143L/wskey#123]
不论是否重新抓取，都显示：

## 开始执行... 2021-12-14 12:43:14

```
--------------------

5700端口检查通过

当前脚本版本: 1118
--------------------

Verification passed
--------------------

WSKEY格式错误
--------------------

执行完成
--------------------

## 执行结束... 2021-12-14 12:43:15 耗时 1 秒
```

**Comment by Zy143L** [comment]
没问题啊..写了 wskey格式错误
正确格式化是
pin=xxxx;wskey=xxxx;

新版没有pin了 但是转换还需要 你自己补上就行了 pin和pt_pin是一个东西

**Comment by ryan016** [comment]
> 没问题啊..写了 wskey格式错误 正确格式化是 pin=xxxx;wskey=xxxx;
> 
> 新版没有pin了 但是转换还需要 你自己补上就行了 pin和pt_pin是一个东西

pin=xxxxxx;wskey=xxxxxxxxijqyIMEHHKYy0-__jJPAqaXBN501oKVzCjxxxxxxqV2EYB;


`格式没错呀，跑脚本就上面的提示……`

**Comment by Zy143L** [comment]
检查末尾的分号 中间不能有空格

**Comment by ryan016** [comment]
检查过了，没有空格，英文逗号，重抓了数次wskey，但还是不行。

**Comment by Zy143L** [comment]
...

**Comment by ryan016** [comment]
> ...

真的很抱歉，添麻烦了！

**Comment by annce** [comment]
wskey，能在分号后添加多个账号么
