### ISSUE TITLE
最近为啥老是提示wskey失效，实际上并没有失效

### ISSUE THREAD

**Issue by GitHub-Stock** [Zy143L/wskey#126]
大大看过来

**Comment by Zy143L** [comment]
你的ip被JD拉黑了 接口可能返回500 403等 这种情况我是默认CK失效的

**Comment by GitHub-Stock** [comment]
喔喔，这样啊，那没事了。话说回复是真滴快

**Comment by Zy143L** [comment]
如果这个对你造成影响的话 修改166行的
`return False` 改成
`return True`

**Comment by GitHub-Stock** [comment]
好的，感谢。主要是因为最近push一大堆报错。所以就随口问一下
