### ISSUE TITLE
2021-12-29今天报错了，麻烦您看下是什么问题的呢，谢谢

### ISSUE THREAD

**Issue by founderme** [Zy143L/wskey#128]
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
未知错误云端, 退出脚本!

**Comment by Zy143L** [comment]
先更换本地ip 年底了 那边估计抽风了 ...我这边测试正常
如果出现大面积RST我会及时更新

**Comment by founderme** [comment]
重启拨号更新了几个IP了，还是一样的Connection aborted，跪求更新下，万分感谢。

**Comment by founderme** [comment]
> 重启拨号更新了几个IP了，还是一样的Connection aborted，跪求更新下，万分感谢。

**Comment by Zy143L** [comment]
行

**Comment by Zy143L** [comment]
已修复 更新脚本即可
