### ISSUE TITLE
未知错误云端, 退出脚本

### ISSUE THREAD

**Issue by dy2898** [Zy143L/wskey#129]
http://43.135.90.23/wskey，这个地址被墙了
5700端口检查通过

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
未知错误云端, 退出脚本!

**Comment by Zy143L** [comment]
先更换本地ip 年底了 那边估计抽风了 ...我这边测试正常
如果出现大面积RST我会及时更新

**Comment by Zy143L** [comment]
已修复 更新脚本即可
