### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by Jumeng-ms** [Zy143L/wskey#13]
有BUG 
不覆盖更新仅仅添加ck 
希望添加查重更新

**Comment by Zy143L** [comment]
删掉重复的 包括现有的 只保留wskey去执行
针对这种情况 一般是用户名存在特殊id 或者中文 已经做过处理了
可以尝试
只保修wskey 删掉全部对应的jd_cookie 然后执行脚本 执行两次 看看会不会重复添加
请发截图给我
