### ISSUE TITLE
端口没错啊 为什么不能运行,刚更新了

### ISSUE THREAD

**Issue by Zhangjinhua512** [Zy143L/wskey#130]
5200端口检查失败, 如果改过端口, 请在变量中声明端口 
在config.sh中加入 export QL_PORT="端口号"

如果你很确定端口没错, 还是无法执行, 在GitHub给我发issus

**Comment by Zy143L** [comment]
你确定是5200吗? 你这个端口是怎么改的呢

**Comment by Zhangjinhua512** [comment]
就是装青龙的时候在docker-compose.yml  设置的5200,

**Comment by Zy143L** [comment]
docker配置的端口无需修改..这个是用于青龙nginx端口修改后的修改

**Comment by Zhangjinhua512** [comment]
好的,谢谢,可是出现了新问题
新wskey

WSKEY转换接口出错, 请稍后尝试, 脚本退出
接口出错怎么回事呢

**Comment by Zy143L** [comment]
这个就得看你网络了..这个是直接走jd服务器的请求

**Comment by 17huiwei** [comment]
我也是，提示端口不对，我已经在环境变量和config.sh里面都设置了呀
