### ISSUE TITLE
无法检测ck失效

### ISSUE THREAD

**Issue by changzhongxinxin** [Zy143L/wskey#132]
这个只有ck失效才会转换，而我的ck失效了他还检测未失效，有没有**青龙全自动更新ck**的拉取命令啊，这个是强制转换，不管有没有失效

**Comment by smilingpoplar** [comment]
同样情况，ck故意改失效，wskey脚本还是报ck有效

**Comment by changzhongxinxin** [comment]
对的，除非吧ck删了再运行脚本


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月31日(周五) 中午12:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zy143L/wskey] 无法检测ck失效 (Issue #132)




 
同样情况，ck故意改失效，wskey脚本还是报ck有效
 
&mdash;

**Comment by Zy143L** [comment]
已修复 系京东更换接口

**Comment by changzhongxinxin** [comment]
刚换了ddo大佬的青龙全自动更新ck😳


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月31日(周五) 中午12:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zy143L/wskey] 无法检测ck失效 (Issue #132)




 
已修复 系京东更换接口
 
&mdash;
