### ISSUE TITLE
青龙2.10.13脚本无法更新

### ISSUE THREAD

**Issue by celetor** [Zy143L/wskey#133]
青龙版本v2.10.13，使用`ql repo https://github.com/Zy143L/wskey.git "wskey"`命令发现脚本没有更新，尝试使用`ql raw https://raw.githubusercontent.com/Zy143L/wskey/main/wskey.py`发现以下错误
![image](https://user-images.githubusercontent.com/86599970/147848951-da86af6e-54a0-445c-9c12-ffbca383d6aa.png)

**Comment by Zy143L** [comment]
检查青龙问题 我这边测试OK

**Comment by baibaikk** [comment]
今天我也是出现这个问题

**Comment by Zy143L** [comment]
![image](https://user-images.githubusercontent.com/21352718/148014706-d2bf0c7a-be5d-4497-beb8-74393e8b818b.png)
