### ISSUE TITLE
wskey正常，转换就会出现失败问题

### ISSUE THREAD

**Issue by kittyzero520** [Zy143L/wskey#138]
## 开始执行... 2022-01-08 17:37:16

--------------------

5700端口检查通过

Default Server Check OK

当前脚本版本: 10102
--------------------

Verification passed
--------------------

pt_pin=Business;检索成功

不检查账号有效性
--------------------

pin=Business;WsKey状态正常

wskey转换成功

账号启用
--------------------

pt_pin=happy52;检索失败

新wskey

pin=happy52;WsKey状态失效

执行完成
--------------------
Telegram 推送打开
企业微信机器人 推送打开

**Comment by Zy143L** [comment]
检查pin的问题
![image](https://user-images.githubusercontent.com/21352718/148650414-46ebf2ee-e155-4e72-b9c3-eb521eaf28d6.png)

测试正常

**Comment by kittyzero520** [comment]
重启也不行，pin怎么看问题

**Comment by Zy143L** [comment]
加我 https://t.me/Shizuku_moe
