### ISSUE TITLE
生成的ptkey失效

### ISSUE THREAD

**Issue by wanthigh** [Zy143L/wskey#139]
使用最新的生成出来的ptkey，跑脚本的时候提示cookie无效

**Comment by Zy143L** [comment]
重启青龙环境..有些脚本会持久化cookie

**Comment by wanthigh** [comment]
我的是直接使用node js跑的。。没用青龙

**Comment by Zy143L** [comment]
你手动用转出来的ptkey去curl下jd那边的api
看看返回值信息
莫非是检测接口又失效了?不应该 昨天才测的

**Comment by wanthigh** [comment]
我把我之前的ptkey去掉，然后调你的接口重新生成的就可以了，但之前的如果没去掉，会用老的ptkey先调用你的验证接口，应该直接通过了导致没有生成新的

**Comment by Zy143L** [comment]
验证接口都是京东的..我只提供sign计算

**Comment by wanthigh** [comment]
难不成jd出毛病了。。之前都没有问题

**Comment by Zy143L** [comment]
源码那边都有 你可以看下

**Comment by wanthigh** [comment]
好的，我看了，check_ck的url换了。。

**Comment by kittyzero520** [comment]
> 重启青龙环境..有些脚本会持久化cookie

感谢，我试试重启

**Comment by kittyzero520** [comment]
> 好的，我看了，check_ck的url换了。。

你的可以了不，我的还是很多失败

**Comment by Zy143L** [comment]
加我 https://t.me/Shizuku_moe
