### ISSUE TITLE
青龙昨晚自动更新后就不能转换了

### ISSUE THREAD

**Issue by Acexone** [Zy143L/wskey#141]
![image](https://user-images.githubusercontent.com/78152688/149270208-28f4ea97-d3ca-461a-97e3-7e83eda80cc7.png)

**Comment by wapearoudy** [comment]
遇到了同样的问题

**Comment by pujie1216** [comment]
脚本管理,打开py文件
查找 _id 修改为 id
跳过 e_id 或者全部修改都行

**Comment by wapearoudy** [comment]
重新更新一下青龙，就正常了，亲测有效

**Comment by Acexone** [comment]
更新镜像后好了

**Comment by Acexone** [comment]
> 重新更新一下青龙，就正常了，亲测有效

能运行了，但是问题好像更严重了，每运行一次就重复添加一遍ck。。。

**Comment by Zy143L** [comment]
在看了

**Comment by Acexone** [comment]
> 在看了
测试运行了几次，现在是pt_pin都有的，但是提示检索失败，然后环境变量里重新又加了一遍JD_COOKIE，刚才运行三遍，一模一样的pin的ck加了三遍了。。。

**Comment by Zy143L** [comment]
> > 在看了
> > 测试运行了几次，现在是pt_pin都有的，但是提示检索失败，然后环境变量里重新又加了一遍JD_COOKIE，刚才运行三遍，一模一样的pin的ck加了三遍了。。。

行好 知道了 在装新的青龙
