### ISSUE TITLE
更新后，wskey跑不起来

### ISSUE THREAD

**Issue by xiongerdong** [Zy143L/wskey#145]
Traceback (most recent call last):
  File "wskey.py", line 492, in <module>
    ql_id = ['_id', 'id'][get_version()]
  File "wskey.py", line 370, in get_version
    version = str(json.loads(res.text)['data']['version'])
KeyError: 'version'

**Comment by fidcz** [comment]
`    try:
        version = str(json.loads(res.text)['data']['version'])
    except:
        return 0`
第370行替换为这段代码，注意缩进。只是我自己的临时方案，具体以作者修复为准

**Comment by yimshing** [comment]
青龙2.10.10 跟上面一样的报错

**Comment by Zy143L** [comment]
已修复 请更新
