### ISSUE TITLE
最新版检测不到JD_WSCK环境变量了

### ISSUE THREAD

**Issue by NaiHeKK** [Zy143L/wskey#146]
大佬，刚更新完跑这个就报
`## 开始执行... 2022-01-14 09:47:17

# 当前总共 21 个 JD_COOKIE，其中：已通过环境变量禁用了 11 个 JD_COOKIE。

--------------------

5700端口检查通过
青龙面板版本: 2.11.0
Default Server Check OK
--------------------

当前脚本版本: 10114
--------------------

Verification passed
--------------------

未添加JD_WSCK变量

## 执行结束... 2022-01-14 09:47:24 耗时 7 秒`
麻烦大佬看一下

**Comment by Zy143L** [comment]
检查你的青龙环境 针对JD_WSCK部分并没有修改
