### ISSUE TITLE
版本识别错误，导致转换失败

### ISSUE THREAD

**Issue by mjyhj** [Zy143L/wskey#149]
下午1点多的时候，重启了一下青龙容器，但是没有更新版本。
目前强制刷新了浏览器缓存，依旧还是2.10.3。
但是log显示识别成2.11了，导致转换失效。
![1](https://user-images.githubusercontent.com/22577418/149627339-386f4ed5-fc08-4b28-9c2b-be7a53cd7e0e.png)

目前手动改成，就转换正常
        logger.info("青龙面板版本: " + version)
        if version > '2.10.13':
            return 0
        else:
            return 0
![2](https://user-images.githubusercontent.com/22577418/149627423-16e8acec-8f89-4b14-aef2-15dc82d54559.png)

**Comment by Zy143L** [comment]
这个识别是直接走青龙接口的
说明你前后端有冲突,..

**Comment by mjyhj** [comment]
> 这个识别是直接走青龙接口的 说明你前后端有冲突,..

我现在实际就是2.10.3的，就是不知道为什么会这样。重启了容器就成这样了

**Comment by Zy143L** [comment]
你也能看到
`url = 'http://127.0.0.1:{0}/api/system'.format(port)`
我是直接请求青龙的API识别的

**Comment by mjyhj** [comment]
> 你也能看到 `url = 'http://127.0.0.1:{0}/api/system'.format(port)` 我是直接请求青龙的API识别的

要不要给你远程看看

**Comment by Zy143L** [comment]
没办法 你先看能用不 
这个修正只是处理重复添加的问题
你多跑下脚本 如果出现 检索失败 新wskey的提示 证明还得用新的

**Comment by mjyhj** [comment]
> 没办法 你先看能用不 这个修正只是处理重复添加的问题 你多跑下脚本 如果出现 检索失败 新wskey的提示 证明还得用新的

直接会报错，跑不了
![3](https://user-images.githubusercontent.com/22577418/149627842-f31e37c4-807b-43eb-9b61-426e0b80e102.png)

**Comment by Zy143L** [comment]
奇葩..的 我也没办法 你先改着用吧 往后看看情况

**Comment by mjyhj** [comment]
> 奇葩..的 我也没办法 你先改着用吧 往后看看情况

OK

**Comment by mjyhj** [comment]
> 奇葩..的 我也没办法 你先改着用吧 往后看看情况
我现在很奇怪，API是2.11，实际还是2.10.3，nolan都能正常用。
建议直接判断_id是否存在，不存在用id。
不用判断版本号
![4](https://user-images.githubusercontent.com/22577418/149628347-4c55684a-7706-437b-9cae-661d131878b2.png)

**Comment by Zy143L** [comment]
行 加入清单了
