### ISSUE TITLE
询问您脚本运行的频次。。。

### ISSUE THREAD

**Issue by nethawkhu** [Zy143L/wskey#15]
默认好像是4小时运行一次，如果我改成1小时运行一次或者更短的时间运行一次，会产生什么不良后果吗？

其实问这个问题的原因是，我想知道，您的脚本判断一个CK是否有效，需要动用WSKEY去京东服务器认证吗？我怕验证频次太多WSKEY挂了。。。

**Comment by Zy143L** [comment]
1. 可能有不良后果(例如京东api403错误
2. 判断ck是通过pt_key去api请求的 和wskey没关系 
3. 判断wskey的是wskey转换pt_key如果转不出 那就是wskey失效了

**Comment by Zy143L** [comment]
现在加了冗余机制 你可以改1小时一次 错误会重试或者退出的
