### ISSUE TITLE
ql 2.11.0 转换失败

### ISSUE THREAD

**Issue by danwangshi** [Zy143L/wskey#150]
5700端口检查通过
青龙面板版本: 2.11.0
Default Server Check OK
--------------------

当前脚本版本: 10114
--------------------

Verification passed
--------------------

pt_pin=830791XXXX661;检索成功

pt_pin=830791XXXXX661;状态失效

JD接口转换失败, 默认WsKey失效

pt_pin=830791XXXX661;账号禁用

账号禁用成功

**Comment by mjyhj** [comment]
> ## 5700端口检查通过
> 青龙面板版本: 2.11.0
> Default Server Check OK
> ## 当前脚本版本: 10114
> ## Verification passed
> pt_pin=830791XXXX661;检索成功
> 
> pt_pin=830791XXXXX661;状态失效
> 
> JD接口转换失败, 默认WsKey失效
> 
> pt_pin=830791XXXX661;账号禁用
> 
> 账号禁用成功

现在转换会黑IP，你换个IP就能转
