### ISSUE TITLE
ql v2.10.10转换失败

### ISSUE THREAD

**Issue by yimshing** [Zy143L/wskey#151]
hi，

log出现以下错误

## 开始执行... 2022-01-17 12:11:02

/usr/local/bin/task: line 113: /usr/bin/timeout: Argument list too long

## 执行结束... 耗时 -1642392662 秒

**Comment by Zy143L** [comment]
你的环境变量炸了..重启青龙

**Comment by yimshing** [comment]
> 
重启了vps不行，单独用ql update重启又会升级版本，目前无解
