### ISSUE TITLE
转换后，去看环境变量那里。没有任何变化。。青龙V2.10.6

### ISSUE THREAD

**Issue by mightydaduser** [Zy143L/wskey#152]
三个wskey 运行日志如下，然而没有新增CK

## 开始执行... 2022-01-17 17:07:48

无推送文件

--------------------

5700端口检查通过
Default Server Check OK
--------------------

当前脚本版本: 10114
--------------------

Verification passed
--------------------

pt_pin=jd_xxx1;检索成功

pt_pin=jd_xxx1;状态正常

pt_pin=jd_xxx1;账号有效

账号启用
--------------------

--------------------

pt_pin=jd_xxx2;检索成功

pt_pin=jd_xxx2;状态正常

pt_pin=jd_xxx2;账号有效

账号启用
--------------------

--------------------

pt_pin=xxx3;检索成功

pt_pin=xxx3;状态正常

pt_pin=xxx3;账号有效

账号启用
--------------------

--------------------

执行完成
--------------------

## 执行结束... 2022-01-17 17:07:50 耗时 2 秒

**Comment by Zy143L** [comment]
检索成功 说明JD_COOKIE变量中已经存在了

**Comment by mightydaduser** [comment]
> 

大佬，这不科学诶，我重启了青龙，还是没有，我重启后再运行，还是没有。莫不是我的青龙出了问题？但是也是最近新run 的青龙呀

**Comment by mightydaduser** [comment]
大佬，对不起，是乌龙，是三个老客户，有CK 在，对不起打扰了，我第一次搞wskey，溜了溜了

**Comment by Rachel-Green** [comment]
> 检索成功 说明JD_COOKIE变量中已经存在了

是要先删除JD_COOKIE再执行转换脚本吗

**Comment by Rachel-Green** [comment]
> > > 检索成功 说明JD_COOKIE变量中已经存在了
> > 
> > 
> > 是要先删除JD_COOKIE再执行转换脚本吗
> 
> 不用 已经添加过的 会更新 没添加的才会添加

但我也是cookie值没变化诶？还是说要当前cookie过期了才会更新呢？
