### ISSUE TITLE
WSKEY转换接口出错, 请稍后尝试, 脚本退出

### ISSUE THREAD

**Issue by kepy909** [Zy143L/wskey#154]
## 开始执行... 2022-01-19 15:00:36

--------------------

5700端口检查通过
青龙面板版本: 2.11.0
Default Server Check OK
--------------------

当前脚本版本: 10114
--------------------

Verification passed
--------------------

pt_pin=若陈阳;检索成功

不检查账号有效性
--------------------

WSKEY转换接口出错, 请稍后尝试, 脚本退出

## 执行结束... 2022-01-19 15:00:38 耗时 2 秒

**Comment by Zy143L** [comment]
请修改中文 而且检查抓的pin

**Comment by kepy909** [comment]
## 开始执行... 2022-01-19 17:15:35


--------------------

5700端口检查通过
青龙面板版本: 2.11.0
Default Server Check OK
--------------------

当前脚本版本: 10114
--------------------

Verification passed
--------------------

pt_pin=%E8%8B%A5%E9%99%88%E9%98%B3;检索成功

不检查账号有效性
--------------------

pin=%E8%8B%A5%E9%99%88%E9%98%B3;WsKey状态失效

pt_pin=%E8%8B%A5%E9%99%88%E9%98%B3;账号禁用

账号禁用成功

**Comment by kepy909** [comment]
一个wskey是不是不能同时两台电脑使用？

**Comment by Zy143L** [comment]
不是 你抓的时候 pin就不对可能
