### ISSUE TITLE
国内拉取不了仓库

### ISSUE THREAD

**Issue by wcn666** [Zy143L/wskey#155]
貌似免费代理不能用了，屏蔽了JD仓库，所以现在拉取不了，有啥办法吗

**Comment by asdertypo** [comment]
一样，日志：
开始克隆仓库 https://ghproxy.com/https://github.com/Zy143L/wskey.git 到 /ql/repo/Zy143L_wskey


更新/ql/repo/Zy143L_wskey失败，重新下载全新仓库...

开始克隆仓库 https://ghproxy.com/https://github.com/Zy143L/wskey.git 到 /ql/repo/Zy143L_wskey


更新/ql/repo/Zy143L_wskey失败，请检查网络...

**Comment by Zy143L** [comment]
已更新 ql repo https://e.coding.net/HelloDNS/sign/wskey.git "wskey"

**Comment by 2563411574** [comment]
不能用 好像又被封了

**Comment by Zy143L** [comment]
![image](https://user-images.githubusercontent.com/21352718/150641263-75e74210-139f-4631-acea-3f8d7ef96aa8.png)
没一点问题啊

> 不能用 好像又被封了
