### ISSUE TITLE
WsKey状态失效

### ISSUE THREAD

**Issue by Miroxyz** [Zy143L/wskey#156]
添加成功之后不到两天，WsKey状态失效了。想问下一般是什么原因导致的？

**Comment by Miroxyz** [comment]
> 添加成功之后不到两天，WsKey状态失效了。想问下一般是什么原因导致的？

调试发现ua是安卓的信息，我是用iPhone获取的WsKey，不知道和这个有关系没有？

**Comment by Zy143L** [comment]
这个关系不大 可能原因有
1.从新登录 2.新设备登录 3.修改密码 4.IP风控
目前很大情况是IP风控 换个IP就正常
