### ISSUE TITLE
JD接口转换失败, 默认WsKey失效

### ISSUE THREAD

**Issue by shieber-xie** [Zy143L/wskey#158]
你好，我想问下这个错误怎么解决？ck重新抓取也是一样的
--------------------

5700端口检查通过
Default Server Check OK
--------------------

当前脚本版本: 10114
--------------------

Verification passed
--------------------

pt_pin=jd_655dfd55ffebd;检索失败

新wskey

xxx

JD接口转换失败, 默认WsKey失效

执行完成
-----------------

**Comment by Wyatt323** [comment]
同样的我也有这个问题

**Comment by gutougu** [comment]
换了版本也是这样，只能等作者更新了

**Comment by Zy143L** [comment]
经测试 非脚本问题 系转换频率过高被京东拉黑IP
或者账号风控

**Comment by yyetss** [comment]
> 经测试 非脚本问题 系转换频率过高被京东拉黑IP
> 
> 或者账号风控

经测试账号和IP都没有问题。换一个转换脚本就正常转换了

**Comment by Mr-Coffee666** [comment]
> 经测试 非脚本问题 系转换频率过高被京东拉黑IP 或者账号风控

**Comment by Mr-Coffee666** [comment]
> 经测试 非脚本问题 系转换频率过高被京东拉黑IP 或者账号风控

9000+分的plus新号，第一次使用wskey，同样有这问题

**Comment by Mr-Coffee666** [comment]
> > 经测试 非脚本问题 系转换频率过高被京东拉黑IP 或者账号风控
> 
> 9000+分的plus新号，第一次使用wskey，同样有这问题

所以应该和账号关系不大，应该是jd加强了算法，看大佬如何修复了
