### ISSUE TITLE
接口问题，转换失败，CK会被禁用

### ISSUE THREAD

**Issue by mjyhj** [Zy143L/wskey#159]
接口问题，实则wskey没失效，然后CK会被禁用。
实际wskey和CK都没失效，不需要禁用CK

**Comment by Zy143L** [comment]
接口为JDAPI 你可以自己改改逻辑

**Comment by Kaystar** [comment]
> 接口为JDAPI 你可以自己改改逻辑

![4D82E5F7-146F-422C-9CF7-5CEF28460FF8](https://user-images.githubusercontent.com/71498983/151849965-186fc451-c133-48ac-95c6-84c66020153f.png)
晚上好多人都出现这个问题

**Comment by gthanmon** [comment]
同样存在这个问题

**Comment by wssh13** [comment]
在线等

**Comment by yyetss** [comment]
在线等大佬修复

**Comment by Zy143L** [comment]
...等我修复没用啊..
这是京东的接口...如果默认失效的操作对你们造成影响 修改229行改为 return True, jd_ck

**Comment by yimshing** [comment]
换ip不知道行不行，我也发现是这样

**Comment by yyetss** [comment]
> 换ip不知道行不行，我也发现是这样
换IP不行的。我试过了。如楼上大佬说的改229行目前有用

**Comment by INFWOLAD** [comment]
> 

但是改229好像只是让当前cookie不失效，失效了之后也没办法转换吧。

**Comment by mjyhj** [comment]
我目前注释524这一行ql_disable(eid)
这样接口失效，或者wskey真失效，也不会主动去禁用CK

**Comment by songmyc** [comment]
我也出现了这个问题

**Comment by Zy143L** [comment]
已更新
