### ISSUE TITLE
大神 青龙2.2面板 还能有机会用上嘛？

### ISSUE THREAD

**Issue by gg8760** [Zy143L/wskey#16]
大神 青龙2.2面板 还能有机会用上嘛？2.2的面板比较佛系，恳请大神能适配下 2.2.版本啊

**Comment by Zy143L** [comment]
2.2面板呢.接口换的太多了 我这边也没2.2的了
还是建议你升级面板
已经排档了 等后面

**Comment by hdstar2009** [comment]
2.2接口换的太多了？就你提供的那个修复ck bug的2.2版本，我一直在用。
新版要弄助力码太烦。看到有人专门更新那个助理码脚本就觉得复杂，一周几更。

**Comment by gg8760** [comment]
> 2.2接口换的太多了？就你提供的那个修复ck bug的2.2版本，我一直在用。
> 新版要弄助力码太烦。看到有人专门更新那个助理码脚本就觉得复杂，一周几更。

是的呀  我也觉得2.2 助力真的好方便，我也一直用的大神的这个2.2，非常方便，希望大神能匹配下，非常感谢啊

**Comment by RedShameA** [comment]
> 2.2接口换的太多了？就你提供的那个修复ck bug的2.2版本，我一直在用。
> 新版要弄助力码太烦。看到有人专门更新那个助理码脚本就觉得复杂，一周几更。

老哥助力码脚本发一个呗

**Comment by Zy143L** [comment]
在排期了 等后面
