### ISSUE TITLE
config加了变量 端口也没错

### ISSUE THREAD

**Issue by yinmai0506** [Zy143L/wskey#160]
![QQ图片20220201112837](https://user-images.githubusercontent.com/83388197/151908957-3f7529ba-109d-4a05-a845-a8c9786de9c8.png)
![QQ图片20220201112902](https://user-images.githubusercontent.com/83388197/151908964-b1a45f1e-ba5b-4a75-8e94-e47315ab8a73.png)

**Comment by gthanmon** [comment]
这里的端口跟你理解的不是一个  把端口删了

**Comment by yinmai0506** [comment]
> 这里的端口跟你理解的不是一个 把端口删了

那应该怎么修改呢

**Comment by gthanmon** [comment]
config里定义的端口删了啊

**Comment by yinmai0506** [comment]
> config里定义的端口删了啊

已经删了 一样端口检查失败

**Comment by Zy143L** [comment]
你改成5700就行了..
这个端口是给内部nginx用的

**Comment by Zy143L** [comment]
已更新
