### ISSUE TITLE
jd接口出错，京东好像是增加了算法

### ISSUE THREAD

**Issue by 1934103887** [Zy143L/wskey#162]

**Comment by zhuiyue132** [comment]
+1

**Comment by lxr760** [comment]
+2

**Comment by char1eslu** [comment]
+3

**Comment by Xeath** [comment]
这个情况是 IP 被黑或者账户被风控。不知道作者未来会不会更新 10.3 的 sign。

**Comment by Zy143L** [comment]
在写新算法了

**Comment by mjyhj** [comment]
> 这个情况是 IP 被黑或者账户被风控。不知道作者未来会不会更新 10.3 的 sign。

我测了，不是IP问题我换过几个都一样，也不是风控问题，要不断转换，才有概率转出来。

**Comment by jerrie610** [comment]
我发现现在接口也不是完全不能用，要多执行几次，就可以转换

**Comment by shishixiu** [comment]
> 我发现现在接口也不是完全不能用，要多执行几次，就可以转换

发现了……奇奇怪怪

**Comment by Zy143L** [comment]
已更新
