### ISSUE TITLE
e.coding.netz这个链接失效了

### ISSUE THREAD

**Issue by lxr760** [Zy143L/wskey#163]
e.coding.netz这个链接失效了

另外，京东应该是升级了接口。现在转换wsk全是失效的

PS:新年快乐，大佬们~

**Comment by Zy143L** [comment]
https://e.coding.net/HelloDNS/sign/wskey.git
测试没问题

**Comment by lyh1980** [comment]
https://e.coding.net/HelloDNS/sign/wskey.git
打开是404
![image](https://user-images.githubusercontent.com/32607157/152076890-b1d1b4e3-4211-4baa-8276-08b6bf09de40.png)

**Comment by Zy143L** [comment]
已更新
