### ISSUE TITLE
Cookie 失效时调用 wskey 更新（task_after.sh 版）

### ISSUE THREAD

**Issue by Xeath** [Zy143L/wskey#166]
#91 是个很不错的方法。
不过青龙提供了 `task_after.sh` 脚本，所以完全可以使用这个实现。
通用方法所以不存在不兼容某库（脚本不存在指定关键词除外），可以直接升级面板或者使用修改版的通知脚本。
缺点就是只有任务完成后才会去判断是否有 Cookie 失效。
```shell
#!/usr/bin/env bash

# Cookie 失效自动启动转换
if [ ! -f "${dir_log}/Zy143L_wskey_lock" ]; then
    if [ `grep -c "cookie已失效" "${log_path}"` -gt 0 ]; then
        # 这里也可以通过判断日志中哪个账户失效，然后只针对这个失效的账户进行更新
        # 代码比较复杂，以后有时间再实现
        echo "# 日志文件：${log_path}"
        echo "# 发现存在已失效 Cookie"
        flock "${dir_log}/Zy143L_wskey_lock" -c "task Zy143L_wskey/wskey.py now; rm -f \"${dir_log}/Zy143L_wskey_lock\"" > /dev/null 2>&1 &
        echo "# 已启动 Zy143l 的 wskey.py 进行 CK 更新"
    fi
fi
```
![Uploading 截屏2022-02-03 上午12.12.02.png…](https://user-images.githubusercontent.com/28760483/152193144-d182c1f9-2ae8-4c33-a8e3-f9c6101bc09e.png)
![截屏2022-02-03 上午12 13 00](https://user-images.githubusercontent.com/28760483/152192834-ca0d30f8-5628-43c6-9856-734a063850a9.png)
![截屏2022-02-01 下午9 53 50](https://user-images.githubusercontent.com/28760483/151981148-98ae1a98-0197-4bc4-ac8c-edf0ff89c88e.png)
最后附赠一个自动清理日志的命令，也是添加到 `task_after.sh`。
这个只是相对 `ql rmlog *` 更加灵活和及时，仅供参考。
如果需要添加，请记得添加在文件最下面，并且预留一定的时间，否则导致读取不到日志。
```shell
find $log_dir -type f -mmin +10 | xargs rm -f
```
`-mmin +10` 表示 10 分钟前（负数表示 10 分钟内）被修改的日志，需要别的时间自己修改。
`find` 其它时间参数
- `-amin` 表示在几分钟内被访问的文件
- `-atime` 表示在几天内被访问的文件
- `-cmin` 表示在几分钟内创建的文件
- `-ctime` 表示在几天内创建的文件
- `-mmin` 表示在几分钟内被修改的文件
- `-mtime` 表示在几天内被修改的文件

**Comment by mjyhj** [comment]
这样不会全部号跑一遍吗？？

**Comment by yimshing** [comment]
暂时因为接口问题还用不上，之后看能不能用楼主的这个试试，谢谢啦

**Comment by Zy143L** [comment]
已更新

**Comment by Xeath** [comment]
> 已更新

我这个不是问题反馈，算是教程帖。
用 task_after.sh 的好处就是，一次设置，不受面板版本的影响，使用魔改 sendNotify 文件也不影响更新。
使用了 flock 做并发限制，即使有任务同时结束也不会多次运行。
已经补充了两张测试结果的截图。
可以的话希望给 pin 一下。

**Comment by sibentianxia** [comment]
腾讯云可以正常转，华为云不行，提示wskey状态失效。怎么回事

**Comment by Zy143L** [comment]
你自己都说了..那肯定是被限制IP了

**Comment by mjyhj** [comment]
> > 已更新
> 
> 我这个不是问题反馈，算是教程帖。 用 task_after.sh 的好处就是，一次设置，不受面板版本的影响，使用魔改 sendNotify 文件也不影响更新。 使用了 flock 做并发限制，即使有任务同时结束也不会多次运行。 已经补充了两张测试结果的截图。 可以的话希望给 pin 一下。


使用了你这个有一个问题，那就是如果有个号没添加wskey的，只是网页抓的CK。
这个号失效后，wskey.py并不会能禁用这个CK，然后导致脚本不断触发运行

**Comment by Xeath** [comment]
> > > 已更新
> > 
> > 
> > 我这个不是问题反馈，算是教程帖。 用 task_after.sh 的好处就是，一次设置，不受面板版本的影响，使用魔改 sendNotify 文件也不影响更新。 使用了 flock 做并发限制，即使有任务同时结束也不会多次运行。 已经补充了两张测试结果的截图。 可以的话希望给 pin 一下。
> 
> 使用了你这个有一个问题，那就是如果有个号没添加wskey的，只是网页抓的CK。 这个号失效后，wskey.py并不会能禁用这个CK，然后导致脚本不断触发运行

自己增加 CheckCK 相关脚本，因为每个人的 CheckCK 脚本不一样，所以这个问题这个并不做讨论。
在 `task Zy143L_wskey/wskey.py now;` 前面增加 `task 你的 CheckCK 脚本地址 now;`
完整示例，注意这个只是示例，别问为什么直接复制后不能用。已经说得很清楚了。
```shell
#!/usr/bin/env bash

# Cookie 失效自动启动转换
if [ ! -f "${dir_log}/Zy143L_wskey_lock" ]; then
    if [ `grep -c "cookie已失效" "${log_path}"` -gt 0 ]; then
        # 这里也可以通过判断日志中哪个账户失效，然后只针对这个失效的账户进行更新
        # 代码比较复杂，以后有时间再实现
        echo "# 日志文件：${log_path}"
        echo "# 发现存在已失效 Cookie"
        flock "${dir_log}/Zy143L_wskey_lock" -c "task 你的 CheckCK 脚本地址 now; task Zy143L_wskey/wskey.py now; rm -f \"${dir_log}/Zy143L_wskey_lock\"" > /dev/null 2>&1 &
        echo "# 已启动 Zy143l 的 wskey.py 进行 CK 更新"
    fi
fi
```

**Comment by mjyhj** [comment]
> > > > 已更新
> > > 
> > > 
> > > 我这个不是问题反馈，算是教程帖。 用 task_after.sh 的好处就是，一次设置，不受面板版本的影响，使用魔改 sendNotify 文件也不影响更新。 使用了 flock 做并发限制，即使有任务同时结束也不会多次运行。 已经补充了两张测试结果的截图。 可以的话希望给 pin 一下。
> > 
> > 
> > 使用了你这个有一个问题，那就是如果有个号没添加wskey的，只是网页抓的CK。 这个号失效后，wskey.py并不会能禁用这个CK，然后导致脚本不断触发运行
> 
> 自己增加 CheckCK 相关脚本，因为每个人的 CheckCK 脚本不一样，所以这个问题这个并不做讨论。 在 `task Zy143L_wskey/wskey.py now;` 前面增加 `task 你的 CheckCK 脚本地址 now;` 完整示例，注意这个只是示例，别问为什么直接复制后不能用。已经说得很清楚了。
> 
> ```shell
> #!/usr/bin/env bash
> 
> # Cookie 失效自动启动转换
> if [ ! -f "${dir_log}/Zy143L_wskey_lock" ]; then
>     if [ `grep -c "cookie已失效" "${log_path}"` -gt 0 ]; then
>         # 这里也可以通过判断日志中哪个账户失效，然后只针对这个失效的账户进行更新
>         # 代码比较复杂，以后有时间再实现
>         echo "# 日志文件：${log_path}"
>         echo "# 发现存在已失效 Cookie"
>         flock "${dir_log}/Zy143L_wskey_lock" -c "task 你的 CheckCK 脚本地址 now; task Zy143L_wskey/wskey.py now; rm -f \"${dir_log}/Zy143L_wskey_lock\"" > /dev/null 2>&1 &
>         echo "# 已启动 Zy143l 的 wskey.py 进行 CK 更新"
>     fi
> fi
> ```

很好，不过先跑wskey，再跑checkck，效果更佳

**Comment by Wake2020** [comment]
最新版的青龙，这个脚本失效了，请问改怎么修改呢?
提示信息：  
log: No such file or directory
/ql/data/config/task_after.sh: line 5: [: -gt: unary operator expected

**Comment by WhitLor** [comment]
大佬，请教一下，我因为网络问题无法拉库ql repo https://github.com/Zy143L/wskey.git "wskey"，但是正在使用的库里集成了这个脚本(shufflewzc_faker3_main/jd_wskey.py)，请问您提供的task_after.sh脚本中的“Zy143L_wskey_lock”应该如何对应修改呢，纯代码小白QAQ

**Comment by yunyun9812** [comment]
能否直接判断 是否有被禁用的JD_COOKIE变量 有则调用wskey转换
因为一般Cookie检测脚本发现Cookie失效时都会禁用对应的JD_COOKIE变量，检测这个变量比检测脚本日记直接通用简单

**Comment by Zy143L** [comment]
> 能否直接判断 是否有被禁用的JD_COOKIE变量 有则调用wskey转换 因为一般Cookie检测脚本发现Cookie失效时都会禁用对应的JD_COOKIE变量，检测这个变量比检测脚本日记直接通用简单

本身就是从wskey去轮 不管JD_COOKIE的启用与否 只判断是否存在和有效时效

**Comment by yunyun9812** [comment]
> 最新版的青龙，这个脚本失效了，请问改怎么修改呢? 提示信息： log: No such file or directory /ql/data/config/task_after.sh: line 5: [: -gt: unary operator expected

    if [ `grep -c "已失效,自动禁用成功" "${dir_log}/${log_path}"` -gt 0 ]; then
如上 在${log_path}前加上 ${dir_log}/
