### ISSUE TITLE
更新后仍然提示JD接口转换失败

### ISSUE THREAD

**Issue by gz83** [Zy143L/wskey#171]
更新脚本到最新版后仍然提示JD接口转换失败。

**Comment by Zy143L** [comment]
检查wskey有效性..并考虑下IP是否被拉黑的问题

**Comment by Zy143L** [comment]
从新更新

**Comment by gz83** [comment]
> 从新更新
更新脚本提示：
Fetching origin
HEAD is now at 3535c4e Merge branch 'main' of https://github.com/Zy143L/wskey into main
Auto-merging wskey.py
CONFLICT (content): Merge conflict in wskey.py
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.

执行时提示
## 开始执行... 2022-02-02 20:27:46

  File "wskey.py", line 13
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax

## 执行结束... 2022-02-02 20:27:46 耗时 0 秒

**Comment by gz83** [comment]
> 删掉整个仓库 从新拉取 期间变更了几次

还是这样

**Comment by Zy143L** [comment]
从镜像地址拉取吧..

**Comment by gz83** [comment]
> 从镜像地址拉取吧..

可以了，谢谢大佬
