### ISSUE TITLE
接口转换失败

### ISSUE THREAD

**Issue by Wangsc1** [Zy143L/wskey#173]
已更新最新：

5600端口检查通过
青龙面板版本: 2.11.2
Default Server Check OK
--------------------

当前脚本版本: 20202
--------------------

pt_pin=xxx;检索成功

不检查账号有效性
--------------------

JD接口转换失败, 默认WsKey失效

10 秒后重试，剩余次数：7

JD接口转换失败, 默认WsKey失效

10 秒后重试，剩余次数：6

JD接口转换失败, 默认WsKey失效

10 秒后重试，剩余次数：5

JD接口转换失败, 默认WsKey失效

10 秒后重试，剩余次数：4

JD接口转换失败, 默认WsKey失效

10 秒后重试，剩余次数：3

JD接口转换失败, 默认WsKey失效

10 秒后重试，剩余次数：2

JD接口转换失败, 默认WsKey失效

10 秒后重试，剩余次数：1

**Comment by yimshing** [comment]
情况一样

**Comment by cmazfuture** [comment]
情况一样，重新抓了wskey。换了ip 还是不行

**Comment by ttiny18** [comment]
用10114版多试几次可以转换成功  用新版没一个转换成功的  都是重试10次都是接口问题

**Comment by Zy143L** [comment]
从新拉库..已经回滚脚本
