### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by w900316** [Zy143L/wskey#176]
![IMG_20220202_211100](https://user-images.githubusercontent.com/57336092/152160189-e84ae115-c42f-42d9-ad85-4a3e0c3f462b.jpg)
新版本全报错啊

**Comment by Zy143L** [comment]
更换IP后重试

**Comment by w900316** [comment]
> 更换IP后重试

换了ip还是不行

**Comment by Zy143L** [comment]
https://t.me/Shizuku_moe

**Comment by Wyatt323** [comment]
![image](https://user-images.githubusercontent.com/71224625/152164559-004f6d2a-fbd5-4946-b0cc-8f9694645f39.png)
大佬，这个又是啥问题啊
