### ISSUE TITLE
脚本无法区分后缀不同账号

### ISSUE THREAD

**Issue by chyaww** [Zy143L/wskey#18]
我有两个账号abc、abc1，运行脚本日志如下：

pt_pin=abc 检索成功

pt_pin=abc1 状态正常

pt_pin=abc 账号有效
--------------------

pt_pin=abc1 检索成功

pt_pin=abc1 状态正常

pt_pin=abc1 账号有效

实际只把abc1的wskey转成了cookie保存到环境变量，abc的wskey并没有转换和保存到环境变量

**Comment by Zy143L** [comment]
可否详细提供下信息
Tg: https://t.me/Shizuku_moe
