### ISSUE TITLE
新版禁用Wskey在禁用状态下依然会被脚本转换为新Cookie

### ISSUE THREAD

**Issue by sanqianyanyi** [Zy143L/wskey#181]
在新版的逻辑之下，禁用的Wskey，在进行查询Cookie是否可用的情况下，依然会检测禁用的Wskey，在手动禁用Wskey的情况下，生成新的Cookie，并且正常启用。这样会启动一些暂时不想启用的账号。

**Comment by Xeath** [comment]
这个看起来是 python 或者青龙的问题，禁用后还是会向环境变量传递 wskey，我之前就遇到过，似乎过一段时间或者重启容器就好了。

**Comment by Zy143L** [comment]
青龙的毛病 重启就好了

**Comment by Zy143L** [comment]
wskey是用过系统变量传递过去的 如果禁用了 就不会检测到wskey
这个情况是青龙的毛病 之前有碰到过 重启就好了

**Comment by sanqianyanyi** [comment]
了解，谢谢您

**Comment by sanqianyanyi** [comment]
> wskey是用系统变量传递过去的 如果禁止了就不会检测key这种 情况是龙的毛病 之前有过过青灯到过重启就好了

重启青龙之后已经解决该问题，十分感谢您
