### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by siyue666** [Zy143L/wskey#182]
用了很久的wskey全部转换失败，重新抓也不行
![Screenshot_2022-02-06-10-53-25-30](https://user-images.githubusercontent.com/87256859/152666164-47bf0fc7-8993-4a61-9f3a-5dcce6d7bae8.jpg)

**Comment by Xeath** [comment]
看样子 `getToken`  返回了 `xxx`，可能是 IP 被黑。
上个版本别人 [162#issuecomment-1026764048](https://github.com/Zy143L/wskey/issues/162#issuecomment-1026764048) 多试几次就出来，我自己测试也是这样。
设置一下 `WSKEY_TRY_COUNT` 看看。

**Comment by Zy143L** [comment]
你说..有没有一种可能 我是说可能... 你的IP黑了或者wskey到期了

**Comment by Xeath** [comment]
> 看样子 `getToken` 返回了 `xxx`，可能是 IP 被黑。 上个版本别人 [162#issuecomment-1026764048](https://github.com/Zy143L/wskey/issues/162#issuecomment-1026764048) 多试几次就出来，我自己测试也是这样。 设置一下 `WSKEY_TRY_COUNT` 看看。

看你截图似乎使用了 `QL_WSCK`，不知道你的更新频率多长，我之前 `QL_WSCK` + 每个小时更新一次也出现过全部不能更新的情况。

刚刚测试了两天前抓的 WSKEY，能过正常转换。有必要的话建议换成 `WSKEY_UPDATE_HOUR` + 每小时运行 `wskey.py`。

![截屏2022-02-06 下午1.10.00](https://user-images.githubusercontent.com/28760483/152668549-8fd7f43a-73c7-485d-8732-c91227e40636.png)
