### ISSUE TITLE
在不设置WSKEY_UPDATE_HOUR时能否去掉转换出的ck中的时间戳

### ISSUE THREAD

**Issue by gthanmon** [Zy143L/wskey#185]
如题，不设置WSKEY_UPDATE_HOUR时应该用不到时间戳吧？

**Comment by ayurnero** [comment]
建议可以设置变量以决定要不要时间戳，有时间戳的话发现某些脚本运行不正常

**Comment by mjyhj** [comment]
> 建议可以设置变量以决定要不要时间戳，有时间戳的话发现某些脚本运行不正常

什么脚本，也不关事吧

**Comment by Xeath** [comment]
将错误的日志晒出，或者自己先在 ck 最后面增加英文分号 ; 看看是否能够正常运行。
而且这个问题更多是脚本问题。

**Comment by yyetss** [comment]
现在有概率会提示wskey已失效，其实是没有失效的，转换时间已经单独调整过了，这个问题会不会是同时转换的人多了的原因呀
![10BEDE88-8616-4584-A66B-BE0897362455](https://user-images.githubusercontent.com/13871776/153705717-e30473bb-3ac0-4159-b3ff-60613d812cfe.png)

**Comment by Xeath** [comment]
> 现在有概率会提示wskey已失效，其实是没有失效的，转换时间已经单独调整过了，这个问题会不会是同时转换的人多了的原因呀
> 
> ![10BEDE88-8616-4584-A66B-BE0897362455](https://user-images.githubusercontent.com/13871776/153705717-e30473bb-3ac0-4159-b3ff-60613d812cfe.png)
> 
> 
> 
> 
不清楚，不排除有这种可能。我自己是通过间隔把每个账户的更新间隔错开（手动改时间戳），目前没有遇到你这个情况。
