### ISSUE TITLE
File "wskey.py", line 12

### ISSUE THREAD

**Issue by dawei233** [Zy143L/wskey#186]
## 开始执行... 2022-02-10 22:00:23

  File "wskey.py", line 12
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax

## 执行结束... 2022-02-10 22:00:24 耗时 1 秒

青龙面版 v2.11.1
拉取命令
ql repo https://github.com/Zy143L/wskey.git "wskey"
然后执行就报错上面的内容

**Comment by dawei233** [comment]
删掉重新拉还一样 我用vscode打开出现有错误，，，我手动下载了这个再放进去就正常了 。。。好奇怪
![image](https://user-images.githubusercontent.com/31338729/153423577-83bb284e-5c9c-44e3-b062-6954069b42e9.png)

**Comment by Zy143L** [comment]
可能是git出毛病了..一般来说 拉镜像就行了

**Comment by dawei233** [comment]
恩恩好的
