### ISSUE TITLE
wskey提示失效

### ISSUE THREAD

**Issue by Salomens** [Zy143L/wskey#188]
![IMG_20220215_185521](https://user-images.githubusercontent.com/64776123/154049712-3016f098-cb84-4bef-ae69-fc85a6e5e32f.jpg)
新转换的wskey提示失效

**Comment by gthanmon** [comment]
同样的问题

**Comment by gthanmon** [comment]
> ![IMG_20220215_185521](https://user-images.githubusercontent.com/64776123/154049712-3016f098-cb84-4bef-ae69-fc85a6e5e32f.jpg) 新转换的wskey提示失效

貌似是ip黑了。。别的服务器正常
