### ISSUE TITLE
会转换失败 抓包出现了这样的情况

### ISSUE THREAD

**Issue by aTenb** [Zy143L/wskey#189]
{
  code: '0',
  tokenKey: 'xxx',
  url: 'https://un.m.jd.com/cgi-bin/app/appjmp'
}

大佬api提供的UA一样 算出来的sign也一样 这是不是导致转换失败的原因?

**Comment by aTenb** [comment]
上面表述有问题 是目前这个逻辑是 开始就获取一次UA 这样导致所有账号都共用的一个UA?

**Comment by aTenb** [comment]
换了ip 也马上黑吗

**Comment by Zy143L** [comment]
拿到xxx有三个可能
1.你IP黑了
2.你号风控了
3.你wskey真失效了

**Comment by aTenb** [comment]
sorry 我刚看了一遍源码 发现大佬接口已经更新了api+getToken 我还在用之前api+wskey的接口,导致的XXX  换成新接口就没问题了. 大佬升级了新接口 老接口不作废的哇?

**Comment by Zy143L** [comment]
懒得删了而已..hhhh
