### ISSUE TITLE
青龙develop版本新修改了 内部的目录地址

### ISSUE THREAD

**Issue by sevensevenmi** [Zy143L/wskey#192]
之前的 /ql/****         
现在的 /ql/data/****
多了一层data目录
大佬可以加个判断，找不到就去 这个目录找

**Comment by Zy143L** [comment]
又改了??啊.晚些处理吧

**Comment by sevensevenmi** [comment]
嗯 是的

**Comment by sevensevenmi** [comment]
-v $PWD/ql:/ql/data \
新版本的部署命令都改了

**Comment by lxr760** [comment]
> -v $PWD/ql:/ql/data 新版本的部署命令都改了

你用的是官方https://hub.docker.com/r/whyour/qinglong版本吗？

 -v $PWD/ql/config:/ql/config \
  -v $PWD/ql/log:/ql/log \
  -v $PWD/ql/db:/ql/db \
  -v $PWD/ql/repo:/ql/repo \
  -v $PWD/ql/raw:/ql/raw \
  -v $PWD/ql/scripts:/ql/scripts \


目录没变

**Comment by sevensevenmi** [comment]
跪求小伙子 切换一下分支

**Comment by sevensevenmi** [comment]
> > -v $PWD/ql:/ql/data 新版本的部署命令都改了
> 
> 你用的是官方[https://hub.docker.com/r/whyour/qinglong版本吗？](https://hub.docker.com/r/whyour/qinglong%E7%89%88%E6%9C%AC%E5%90%97%EF%BC%9F)
> 
> -v $PWD/ql/config:/ql/config -v $PWD/ql/log:/ql/log -v $PWD/ql/db:/ql/db -v $PWD/ql/repo:/ql/repo -v $PWD/ql/raw:/ql/raw -v $PWD/ql/scripts:/ql/scripts \
> 
> 目录没变
> 
> 去telegram群里看了下也没有你说的-v $PWD/ql:/ql/data

切换到develop  去看看吧 遇到凡事 不要杠 自己去验证

**Comment by lxr760** [comment]
> > > -v $PWD/ql:/ql/data 新版本的部署命令都改了
> > 
> > 
> > 你用的是官方[https://hub.docker.com/r/whyour/qinglong版本吗？](https://hub.docker.com/r/whyour/qinglong%E7%89%88%E6%9C%AC%E5%90%97%EF%BC%9F)
> > -v $PWD/ql/config:/ql/config -v $PWD/ql/log:/ql/log -v $PWD/ql/db:/ql/db -v $PWD/ql/repo:/ql/repo -v $PWD/ql/raw:/ql/raw -v $PWD/ql/scripts:/ql/scripts \
> > 目录没变
> > 去telegram群里看了下也没有你说的-v $PWD/ql:/ql/data
> 
> 切换到develop 去看看吧 遇到凡事 不要杠 自己去验证

我有杠？   卧槽     你自己讨论的时候不标注develop     难道就要默认所有人都用的跟你一样

**Comment by sevensevenmi** [comment]
> > > > -v $PWD/ql:/ql/data 新版本的部署命令都改了
> > > 
> > > 
> > > 你用的是官方[https://hub.docker.com/r/whyour/qinglong版本吗？](https://hub.docker.com/r/whyour/qinglong%E7%89%88%E6%9C%AC%E5%90%97%EF%BC%9F)
> > > -v $PWD/ql/config:/ql/config -v $PWD/ql/log:/ql/log -v $PWD/ql/db:/ql/db -v $PWD/ql/repo:/ql/repo -v $PWD/ql/raw:/ql/raw -v $PWD/ql/scripts:/ql/scripts 
> > > 目录没变
> > > 去telegram群里看了下也没有你说的-v $PWD/ql:/ql/data
> > 
> > 
> > 切换到develop 去看看吧 遇到凡事 不要杠 自己去验证
> 
> 我有杠？ 卧槽 你自己讨论的时候不标注develop 难道就要默认所有人都用的跟你一样

我说的是让加判断小伙子 你自己看清楚好不好 不是让修改 你这 真是搞笑

**Comment by Zy143L** [comment]
跟随dev版本的demo已经做好了 等青龙合并主线后会第一时间同步
