### ISSUE TITLE
请问正常情况下cookie转换1次能用多久？

### ISSUE THREAD

**Issue by lxr760** [Zy143L/wskey#193]
我转换1次以后，24h不到就失效，所以我每隔12h转换1次

请问是我抓的wsk有问题？    还是本身有效期就这样

**Comment by sevensevenmi** [comment]
有效期 不固定 部分账号个把小时就失效  有的 隔天 都不失效，跟账号 网络环境多方因数有关，自己修改crontab

**Comment by Zy143L** [comment]
不保证账号风控情况
