### ISSUE TITLE
是否会首先验证cookie有效呢？

### ISSUE THREAD

**Issue by haohaoget** [Zy143L/wskey#2]
是否首先验证cookie有效后在进行wskey转换呢？

**Comment by Zy143L** [comment]
会

**Comment by Zy143L** [comment]
ck有效 就不转 ck有问题再转 如果转不出 就禁用这个ck

**Comment by cmazfuture** [comment]
![image](https://user-images.githubusercontent.com/71751136/131875210-be51c142-ceaa-43dc-af82-e9323a11dbd8.png)
实际上没有添加账号，是什么原因呢

**Comment by Zy143L** [comment]
应该有加 你刷新下青龙ENV那部分
