### ISSUE TITLE
JD_WSKEY接口抛出错误 尝试重试 更换IP

### ISSUE THREAD

**Issue by jerrie610** [Zy143L/wskey#200]
一直显示这个是什么问题？

暂停10秒

pt_
pin=xxxxxxxxxxxx;检索失败

新wskey

JD_WSKEY接口抛出错误 尝试重试 更换IP
Invalid return character or leading space in header: cookie
暂停10秒

pt_
pin=xxxxxxxx;检索失败

新wskey

JD_WSKEY接口抛出错误 尝试重试 更换IP
Invalid return character or leading space in header: cookie
暂停10秒

**Comment by Zy143L** [comment]
你WSKEY写的格式有问题

**Comment by ZXQ-Kyle** [comment]
新账号

**Comment by ZXQ-Kyle** [comment]
pt_pin=jd_tnIp02R8LG2MsNn;检索失败


新wskey

JD_WSKEY接口抛出错误 尝试重试 更换IP
Invalid header value b'pin=jd_tnIp02R8LG2MsNn;wskey=AAJiJHRYAFAWYlwGW4r0F9nuLMarSRquXVyoZUEewt0kqEHZCK54_ZvjdJeMZWJ7e6ZAamTbpEdeUYf-Fb4qJ2VeiYPhu5pV01hZ9ftw687Tc1nDPHvT-g;\n'
暂停10秒

**Comment by ZXQ-Kyle** [comment]
新账号是会有这个问题，原始数据抓包有个参数pin_hash=-897604817，pin的参数原始数据里也没有了，最新版app

pt_pin=xxxxx; 检索失败

新wskey

JD_WSKEY接口抛出错误 尝试重试 更换IP
Invalid header value b'pin=jd_tnxxxxxx;wskey=xxxxxxxxx;\n'

**Comment by Zy143L** [comment]
https://github.com/Zy143L/wskey/issues/101
