### ISSUE TITLE
大佬，我已经在在config.sh中加入端口了，为什么还是无法转换

### ISSUE THREAD

**Issue by 2029696692** [Zy143L/wskey#203]
![image](https://user-images.githubusercontent.com/43993447/157191682-dc54b607-4c68-4426-b2e3-db713096d517.png)
![1646725987(1)](https://user-images.githubusercontent.com/43993447/157191781-25cb0f24-77b8-4d06-b175-e658e3cb7d2d.png)

**Comment by Zy143L** [comment]
这个是内部端口 不是你docker映射出去的端口.. 你删了看能不能跑

**Comment by 2029696692** [comment]
删了也是提示。刚开始是能用的，我看到科技玩家那个教程后，就加了下端口跟强制转换变量。现在删了也不行
![1646732371(1)](https://user-images.githubusercontent.com/43993447/157209947-1afac667-7d48-4247-8a43-da3f2fee3f16.png)

**Comment by Zy143L** [comment]
删了提示啥型号 5700端口错误吗?

**Comment by Zy143L** [comment]
https://github.com/Zy143L/wskey/blob/main/READ.md#%E5%8F%98%E9%87%8F%E5%A3%B0%E6%98%8E

**Comment by 2029696692** [comment]
我之前是在config.sh加了 QL_PORT 参数  QL_WSCK 参数。后面运行提示“1647端口检查失败...”, 删了之后还是一样

**Comment by Zy143L** [comment]
青龙的毛病..环境变量没清理干净 重启下容器

**Comment by 2029696692** [comment]
大佬牛逼，果然重启就行了。青龙这也太坑了...

**Comment by Zy143L** [comment]
可以考虑把环境变量加到/env这个里面
