### ISSUE TITLE
新版青龙文件路径改变导致脚本找不到auth

### ISSUE THREAD

**Issue by refined-fish** [Zy143L/wskey#206]
# 青龙版本号
v2.11.3 develop
## 变化
原本的/ql/config，/ql/db，/ql/log，/ql/raw等需要映射的目录在新版本中统一更改位置到/ql/data/XXX，只需要映射/data即可，但也导致了文件目录改变，脚本找不到auth
## 不更新就没有问题，只是向作者大大报告一下有这件事

**Comment by Zy143L** [comment]
那个是开发板 我等正式版同步 我会同步更新

**Comment by refined-fish** [comment]
> 那个是开发板 我等正式版同步 我会同步更新

感谢您的回复
