### ISSUE TITLE
青龙2.11.3 develop无法运行脚本

### ISSUE THREAD

**Issue by lucas1024** [Zy143L/wskey#208]
## 开始执行... 2022-03-19 02:41:28
--------------------
5700端口检查通过
没有发现auth文件, 你这是青龙吗???
## 执行结束... 2022-03-19 02:41:28 耗时 0 秒

**Comment by Xeath** [comment]
青龙内置的 `nginx` 启动失败。尝试 `docker exec -it {container_name} nginx` 启动一下 `nginx`

**Comment by lucas1024** [comment]
> 青龙内置的 启动失败。 尝试 启动一下 `nginx``docker exec -it {container_name} nginx``nginx`

0f1c92d7c0a0   whyour/qinglong:develop   "./docker/docker-ent…"   7 days ago    Up 8 hours   0.0.0.0:5700->5700/tcp, :::5700->5700/tcp                       qinglong
bfc0cf7f618e   noobx/jd:v3-bot           "docker-entrypoint.sh"   7 weeks ago   Up 4 weeks   0.0.0.0:5678->5678/tcp, :::5678->5678/tcp                       jd
c91e4f54ceb9   portainer/portainer-ce    "/portainer"             7 weeks ago   Up 4 weeks   8000/tcp, 9443/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp   portainer
root@OpenWrt:~# docker exec -it qinglong nginx
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)
nginx: [emerg] still could not bind()

**Comment by Zy143L** [comment]
和青龙nginx没啥关系 
青龙开发板调整了auth的目录
我这边已经搞好了 等青龙同步到正式版会同步代码
如果你有需求 https://github.com/Zy143L/wskey/blob/2c44397892bae3b92374500522bca9d6db00cd00/wskey.py#L70
改成 `path = '/ql/data/config/auth.json'
