### ISSUE TITLE
请求支持 Openapi, 如果可能的话

### ISSUE THREAD

**Issue by ioxuy** [Zy143L/wskey#209]
使用场景:
不在同一个容器运行 wskey.py 和 jd脚本
单独一个容器跑 wskey.py更新 ck,就算 ck 被非法获取,也存活不了多久
避免wskey被不安全的脚本获取

**Comment by Zy143L** [comment]
..主要是麻烦 还得处理JD_COOKIE过期监控 青龙那边也不能主动回调 写API这些又划不来
wskey的问题 别用不明来源的脚本就行

**Comment by ioxuy** [comment]
> 
好的

**Comment by ioxuy** [comment]
> ..主要是麻烦 还得处理JD_COOKIE过期监控 青龙那边也不能主动回调 写API这些又划不来 wskey的问题 别用不明来源的脚本就行

好的
