### ISSUE TITLE
可以强制更新吗

### ISSUE THREAD

**Issue by 546220777** [Zy143L/wskey#21]
大佬  按照默认的时间几小时检查一次   但是这样会出现有可能刚检查的时候CK没失效 然后就没有转ck  但是过一会儿CK刚好失效了 …… 如果把定时搞成1小时 又怕会有后遗症。所以有没有可能搞成运行的时候直接强制更新ck  因为已知转换的ck起码有24小时失效。这样的话就可以定时个空闲时间运行一次直接强制更新ck

**Comment by EvanDbg** [comment]
可以自己去改sendNotify.js 有cookie过期再调用这个

**Comment by 546220777** [comment]
> 可以自己去改sendNotify.js 有cookie过期再调用这个

大佬求白嫖

**Comment by Zy143L** [comment]
晚些时候
