### ISSUE TITLE
因为脚本异常死循环导致频繁请求1.117.193.*** 麻烦去除一下谢谢

### ISSUE THREAD

**Issue by HimeHome** [Zy143L/wskey#214]
因为脚本异常死循环导致频繁请求1.117.193.*** 麻烦去除一下谢谢

**Comment by Zy143L** [comment]
正在核实 请稍等

**Comment by Zy143L** [comment]
![image](https://user-images.githubusercontent.com/21352718/160221066-8870c272-3bc6-4772-842f-d5caf6ff756e.png)
beegoServer 就没必要来找我解封了吧

**Comment by HimeHome** [comment]
解封下吧。我也不知道青龙这两天自己怎么会这样，我重装吧。不知道是哪里出了问题。

**Comment by Zy143L** [comment]
首先 青龙是nodejs写的 各类脚本也都是nodejs 或者 python
不会出现beegoServer(golang)的字样 还有部分请求是curl 而且一直在刷check_api
能解释一下原因吗?

**Comment by HimeHome** [comment]
这几个月一直转换的好好的，我也不清楚什么原因， 我是小白。。。能帮忙排查下吗？是不是服务器中毒了还是？前几天有更新互助学院的东西CKCK2什么的之类的，昨晚就发现不能转换就来找原因了。

**Comment by Zy143L** [comment]
请仔细检查青龙环境 已对IP解封

**Comment by HimeHome** [comment]
好的，谢谢，我现在马上进行服务器恢复，青龙重装，不知道是哪里个环节出了问题。

**Comment by HimeHome** [comment]
刚进行了一个星期前的快照恢复，禁用了其它仓库的wskey转换，现在还有没有1秒3次的请求？不过还是云端参数解析失败...

**Comment by Zy143L** [comment]
删掉我的脚本 然后从新拉取 IP限制已经全部取消了

**Comment by HimeHome** [comment]
好的，我想应该是前两天更新互助学院的CKCK2问题，我有一天有看到，它竟然运行了20+分钟还在运行，不知道卡在什么地方，本来这脚本也就运行1分钟多，也就是检查CK是否生效

**Comment by HimeHome** [comment]
大佬，我已经删除脚本和仓库，重新拉，怎么还是云端参数解析失败呢？

5700端口检查通过
使用 _id 键值
Default Server Check OK
--------------------
云端参数解析失败
## 执行结束... 2022-03-26 15:55:05 耗时 1 秒

**Comment by Zy143L** [comment]
https://t.me/Shizuku_moe
私聊
