### ISSUE TITLE
请教一下，wekey转换如何解决过一段时间就要登录一次面板的问题，具体会提示如下内容  WSKEY转换 青龙面板WSKEY转换登陆面板失败, 请检查面板状态.

### ISSUE THREAD

**Issue by TLS853** [Zy143L/wskey#219]
请教一下，wekey转换如何解决过一段时间就要登录一次面板的问题，具体会提示如下内容

WSKEY转换
青龙面板WSKEY转换登陆面板失败, 请检查面板状态.

**Comment by Zy143L** [comment]
青龙版本

**Comment by TLS853** [comment]
v2.9.1> 青龙版本

**Comment by Zy143L** [comment]
更新下面板吧..这个版本号太老了

**Comment by TLS853** [comment]
> 更新下面板吧..这个版本号太老了

好的谢谢大佬

**Comment by TLS853** [comment]
已经更新v2.12.0，待我观察下问题有没有解决。
顺便我发现了新的问题，v2.12.0版本的auth.json文件位于/ql/data/config/auth.json，与原来的目录不同。

**Comment by Zy143L** [comment]
这个问题 脚本在前段时间已经修复了
https://github.com/Zy143L/wskey/blob/6c35fbed10eb2058a8cc0206af3a22798ffe163c/wskey.py#L72

**Comment by TLS853** [comment]
好吧才发现是20318版本，谢谢大佬

**Comment by JiZhi-Error** [comment]
> 这个问题 脚本在前段时间已经修复了
> 
> https://github.com/Zy143L/wskey/blob/6c35fbed10eb2058a8cc0206af3a22798ffe163c/wskey.py#L72

但是当我开启两步验证后就提示：青龙面板WSKEY转换登陆面板失败, 请检查面板状态.
关了两步验证就可正常使用

**Comment by FlechazoPh** [comment]
2.10.2 也会出现这个问题，手动登录青龙，点运行就没问题。这个有办法能处理一下么，因为这个版本比较稳定,运行了很长时间，不太想更新到最新版本的青龙了

**Comment by Zy143L** [comment]
> 2.10.2 也会出现这个问题，手动登录青龙，点运行就没问题。这个有办法能处理一下么，因为这个版本比较稳定,运行了很长时间，不太想更新到最新版本的青龙了

你可能得自己抓一下登录路径 然后改下脚本的请求地址 青龙从2.10之后更换了登录的路由地址
