### ISSUE TITLE
大佬能不能搞个按wskey顺序添加ck

### ISSUE THREAD

**Issue by xm1898** [Zy143L/wskey#22]
和ddo的强制更新不一样，这个每次更新一两个会打乱ck顺序

**Comment by Zy143L** [comment]
应该不会吧..我是按照WSKEY顺序来排列的

**Comment by xm1898** [comment]
反正我的青龙2.8.4-004试了新添加ck的会加到最前面去，难道是青龙版本问题？

**Comment by Zy143L** [comment]
我用的是2.9.1版本的
