### ISSUE TITLE
环境变量设置好wskey后提示WSKEY格式错误无法转换

### ISSUE THREAD

**Issue by CedarXia** [Zy143L/wskey#221]
环境变量设置好wskey，跑转换脚本提示WSKEY格式错误。检查了好几遍，wskey抓包没有问题。

脚本日志：
## 开始执行... 2022-04-03 23:05:24

xxxxxxxxxxxx

--------------------

5700端口检查通过
使用 id 键值
Default Server Check OK
--------------------

当前脚本版本: 20318
--------------------

WSKEY格式错误
--------------------

pt_pin=***;检索成功

pt_pin=***;状态正常

pt_pin=***;账号有效

账号启用
--------------------

--------------------

暂停10秒

执行完成
--------------------

## 执行结束... 2022-04-03 23:05:37 耗时 13 秒

**Comment by Zy143L** [comment]
格式应该是 pin=xxxx;wskey=xxxx;
注意分号

**Comment by CedarXia** [comment]
> 格式应该是 pin=xxxx;wskey=xxxx; 注意分号

分号也检查了，是英文版的";"

**Comment by Zy143L** [comment]
重启下青龙 再看有没有这个报错

**Comment by CedarXia** [comment]
> 重启下青龙 再看有没有这个报错

重启青龙之后，还是如下报错，谢谢

账号启用
--------------------

--------------------

暂停10秒

WSKEY格式错误
--------------------

执行完成
--------------------

## 执行结束... 2022-04-03 23:30:00 耗时 14 秒

**Comment by Zy143L** [comment]
说明还是有错误格式的wskey
https://t.me/Shizuku_moe
可以私聊我远程看看
