### ISSUE TITLE
qinglong升级版本的bug

### ISSUE THREAD

**Issue by kele2016** [Zy143L/wskey#225]
`def ql_login():  # 方法 青龙登录(获取Token 功能同上)
    path = '/ql/config/auth.json'  # 设置青龙 auth文件地址
    if not os.path.isfile(path):
        path = '/ql/data/config/auth.json'  # 尝试设置青龙 auth 新版文件地址`
看似解决了。但是实际情况是，青龙从旧版升级到新版本的话，优先级是读取新版的路径，而不是旧版。

应改为
`
def ql_login():  # 方法 青龙登录(获取Token 功能同上)
    path = '/ql/data/config/auth.json'  # 设置青龙 auth新版文件地址
    if not os.path.isfile(path):
        path = '/ql/config/auth.json'  # 尝试设置青龙 auth 文件地址
`

**Comment by Zy143L** [comment]
又不是不能用..而且我还没升级 所以说 我还是/ql/config/auth.json
