### ISSUE TITLE
关于禁用wskey

### ISSUE THREAD

**Issue by hy520gmy1314** [Zy143L/wskey#226]
作者你好，请问能否加入账号失效后能够同时禁用cookie和wskey了，(可以用一个变量控制开关 类似于WSKEY_DISCHECK)，需要的人可以打开，因为删除过期账号同样想删除wskey，所以特此请求，感谢作者！

**Comment by Zy143L** [comment]
有误杀的问题..

**Comment by hy520gmy1314** [comment]
> 有误杀的问题..

好的，感谢你的回复，如果不能实现的话那也没办法，再次感谢🙏

**Comment by Zy143L** [comment]
禁用WSKEY和COOKIE的功能实现很简单
之前就是默认禁用WSKEY的 但是后面发现有误杀的情况
例如 IP黑了 或者WSKEY风控了 这种情况没法判定是失效还是风控

**Comment by hy520gmy1314** [comment]
> 禁用WSKEY和COOKIE的功能实现很简单
> 之前就是默认禁用WSKEY的 但是后面发现有误杀的情况
> 例如 IP黑了 或者WSKEY风控了 这种情况没法判定是失效还是风控

如果能够实现的话，请问能加入这个功能吗？确实有这个需求，通过变量可控开关，默认关闭，需要的开启功能，感谢！

**Comment by Zy143L** [comment]
后期会加上的 不过那个误杀率估计你也不想用hhhhh
