### ISSUE TITLE
我的ip是被ban了么

### ISSUE THREAD

**Issue by RatedR9** [Zy143L/wskey#227]
疑似IP风控等问题 默认为失效

**Comment by Zy143L** [comment]
这个是..京东方面的问题

**Comment by RatedR9** [comment]
但是我手动抓cookie 其他脚本可以运行





------------------ 原始邮件 ------------------
发件人: Zy143L ***@***.***&gt;
发送时间: 2022年4月16日 23:22
收件人: Zy143L/wskey ***@***.***&gt;
抄送: RatedR9 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Zy143L/wskey] 我的ip是被ban了么 (Issue #227)





 
这个是..京东方面的问题

**Comment by Zy143L** [comment]
因为你抓的是cookie 不是wskey 是wskey的接口(京东)被风控了
