### ISSUE TITLE
青龙面板WSKEY转换登陆面板失败, 请检查面板状态.

### ISSUE THREAD

**Issue by heiren001** [Zy143L/wskey#228]
## 开始执行... 2022-05-04 00:38:35

DEBUG模式开启!

--------------------

5700端口检查通过
Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "GET /api/user HTTP/1.1" 401 42
Token失效, 新登陆

Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "POST /api/user/login HTTP/1.1" 200 None
'data'
青龙登录失败, 请检查面板状态!
WSKEY转换

青龙面板WSKEY转换登陆面板失败, 请检查面板状态.

## 执行结束... 2022-05-04 00:38:36 耗时 1 秒
 
**服务时好时坏,ql版本12.1。**

**Comment by Zy143L** [comment]
尝试重启青龙docker后重新执行脚本 我目前也是2.12.1暂时没能复现这个情况

**Comment by heiren001** [comment]
ok 我重启过ql和服务器，反正重启的那一会是不能用，过了俩小时自己就好了，然后就又坏了，很难确定是什么时候不能用的，谢谢大佬

**Comment by heiren001** [comment]
解决了，关闭二步验证就行。
