### ISSUE TITLE
青龙v2.12.2，提示账号: pt_pin=xxxx; WsKey疑似失效, 已禁用Cookie

### ISSUE THREAD

**Issue by kokikoku** [Zy143L/wskey#230]
用HttpCanary抓取wskey。并未发现wskey变化。

--------------------

5700端口检查通过
使用 id 键值
Default Server Check OK
--------------------

当前脚本版本: 20413
--------------------

pt_pin=xxxx;检索成功

xxxx;状态失效

pt_pin=xxxx;WsKey状态失效

pt_pin=xxxx;账号禁用

账号禁用成功
--------------------

WsKey转换脚本

账号: pt_pin=xxxx; WsKey疑似失效, 已禁用Cookie

tg 服务启动
tg 推送成功！
暂停10秒

**Comment by Zy143L** [comment]
因为有风控..我也说明了是疑似

**Comment by kokikoku** [comment]
> 因为有风控..我也说明了是疑似

如何消除呢。换IP？

**Comment by Zy143L** [comment]
换IP咯 延长检查时间 这些 最近比以前风控严格一些

**Comment by kokikoku** [comment]
> 

好的。谢谢。
我最近一般是等提示失效在手动转换的。应该超过24小时转换一次。

**Comment by kokikoku** [comment]
更换IP后出现这个提示：
## 开始执行... 2022-05-05 15:14:46


--------------------

5700端口检查通过
Token失效, 新登陆

使用旧版青龙登录接口
青龙登录失败, 请检查面板状态!
WSKEY转换

青龙面板WSKEY转换登陆面板失败, 请检查面板状态.


tg 服务启动
tg 推送成功！

## 执行结束... 2022-05-05 15:14:49 耗时 3 秒

**Comment by Zy143L** [comment]
青龙版本号多少

**Comment by kokikoku** [comment]
> v2.12.2

**Comment by Zy143L** [comment]
是否启动了2步验证?

**Comment by kokikoku** [comment]
新版本延迟了吗？
禁用两步验证还是不行呢。

## 开始执行... 2022-05-07 14:15:07


--------------------

5700端口检查通过
Token失效, 新登陆

使用 id 键值
Default Server Check OK
--------------------

当前脚本版本: 20413
--------------------

pt_pin=xxxx;检索成功

kokikoku;状态失效

pt_pin=xxxx;WsKey状态失效

pt_pin=xxxx;账号禁用

账号禁用成功
--------------------

WsKey转换脚本

账号: pt_pin=xxxx; WsKey疑似失效, 已禁用Cookie


tg 服务启动
tg 推送成功！
暂停10秒

**Comment by Zy143L** [comment]
这个是JD方面风控问题 不是两步验证问题 两步验证最近会更新

**Comment by kokikoku** [comment]
刚更新境外的IP。境外IP不能用了吗。

**Comment by Zy143L** [comment]
你站在JD的角度想想..一个账号不停在国内国外切换.不封你封谁?

**Comment by kokikoku** [comment]
弄台本地机器感觉不值当了。
刚才发现手机上要重新登录。登录后，wskey有变化，导入青龙暂时转换成功。
v2.12.2与我上个版本不同，是运行转换脚本时面板退出，需要重新登录一次。

**Comment by kokikoku** [comment]
wskey转换成功，账号启用失败

pt_pin=xxxx;检索成功

xxxx;状态失效

pt_pin=xxxx;WsKey状态正常

wskey转换成功

账号启用失败

**Comment by sevensevenmi** [comment]
> 弄台本地机器感觉不值当了。 刚才发现手机上要重新登录。登录后，wskey有变化，导入青龙暂时转换成功。 v2.12.2与我上个版本v2.10.13不同的是，运行转换脚本时面板退出，需要重新登录一次。

解决办法就是重新登录
