### ISSUE TITLE
使用修改sendNotify自动更新Cookie的朋友请务必 删除 QL_WSCK 变量

### ISSUE THREAD

**Issue by mizhihan** [Zy143L/wskey#231]
我再简介里看到了这样一句描述，是不是说cookie失效后可以自动转换吗。我之前都是设置的每天自动定时转换，虽然cookie还未失效。有谁可以教我一下吗，谢谢。

**Comment by mizhihan** [comment]
> 在定时任务执行检测到cookie失效后会调用wskey转换

就是说那个每隔几小时自动检测的功能还是得开启对吗

**Comment by Zy143L** [comment]
或者使用sendNotify变量在检测到推送存在cookie失效关键词时的转换

**Comment by mizhihan** [comment]
> 或者使用sendNotify变量在检测到推送存在cookie失效关键词时的转换啊我就是想知道这个，可以教我怎么设置这个变量吗，谢谢啦

**Comment by Zy143L** [comment]
翻一下以前的issues就有

**Comment by mizhihan** [comment]
> 或者使用sendNotify变量在检测到推送存在cookie失效关键词时的转换



> 翻一下以前的issues就有

好的
