### ISSUE TITLE
【】中招的报警、反诈APP走一波，5月9号凌晨被偷350元豆豆，程序员还搞盗窃，真是耻辱！

### ISSUE THREAD

**Issue by 676077263** [Zy143L/wskey#233]
喷：作为程序员，还是自动化一类的程序员，赚钱方法那么多，居然耻为盗窃！
事件：盗取豆豆350元
措施：大家一起抱团报警吧，反炸APP来一波，有条件的直接110来一波，虽然看上去用户损失并不大，这风气太不好。
恶化：如果大家不报警，有可能恶化为京东内部人员盗取你的资产，然后告诉你是因为你使用了非法程序，随意剽取你的任何弱资产，让你哑口无言
追回：查是肯定能查到的，除非资金不入账，或是J方是线下的，无线上办案经验！其实也无所谓追不追回，总之，程序员盗窃，还是自动化一类的程序员【盗窃】，是天下之大耻！
已举报：
![image](https://user-images.githubusercontent.com/17680886/167561633-c04d5f3e-eabd-4759-ae3e-4cb8966fcf88.png)

**Comment by taohuadongle** [comment]
没看懂，谁偷的？
