### ISSUE TITLE
JD_WSKEY接口抛出错误 

### ISSUE THREAD

**Issue by PUBGEURO** [Zy143L/wskey#236]
暂停10秒

pt_pin=wdVpZzu;检索成功

wdVpZzu;状态失效

JD_WSKEY接口抛出错误 尝试重试 更换IP
Invalid header value b'pin=wdVzu;wskey=AAJ…………svzI;\n'
pt_pin=wdVpZzu;账号禁用

账号禁用成功
——————————
这个是需要换端口吗

**Comment by PUBGEURO** [comment]
其它wskey都能正常转换，就这个不能，改密码再抓包也是报错

**Comment by Zy143L** [comment]
你检查你的wskey格式

**Comment by PUBGEURO** [comment]
改了密码重新抓包也是一样不能用，而且端口5700的脚本都能正常转换，但是5600端口的部分不能正常转换，把服务器重启一遍就能转换提示失败的号，但是维持时间不久，过了一天又开始报错

**Comment by Zy143L** [comment]
'''JD_WSKEY接口抛出错误 尝试重试 更换IP
Invalid header value b'pin=wdVzu;wskey=AAJ…………svzI;\n'
pt_pin=wdVpZzu;账号禁用''''

这部分明显是wskey变量有问题 http抛错了

**Comment by sss1016** [comment]
> 暂停10秒
> 
> pt_pin=wdVpZzu;检索成功
> 
> wdVpZzu;状态失效
> 
> JD_WSKEY接口抛出错误 尝试重试 更换IP Invalid header value b'pin=wdVzu;wskey=AAJ…………svzI;\n' pt_pin=wdVpZzu;账号禁用
> 
> 账号禁用成功 —————————— 这个是需要换端口吗

我也是这个错误，十几个账号有两个一直这样，不知道该咋整了

**Comment by sss1016** [comment]
> 暂停10秒
> 
> pt_pin=wdVpZzu;检索成功
> 
> wdVpZzu;状态失效
> 
> JD_WSKEY接口抛出错误 尝试重试 更换IP Invalid header value b'pin=wdVzu;wskey=AAJ…………svzI;\n' pt_pin=wdVpZzu;账号禁用
> 
> 账号禁用成功 —————————— 这个是需要换端口吗

检查了一下确实好像是格式错误，最后的; 后面别留空格或者换行符，第一个; 后面留一个空格，这样就可以了，虽然还是显示接口错误，但是能转换ck了
--------------------

暂停10秒

pt_pin=1512DD;检索成功

JD接口错误 请重试或者更换IP
pt_pin=1512DD;WsKey状态正常

wskey转换成功

账号启用
--------------------
