### ISSUE TITLE
不打印日志信息了

### ISSUE THREAD

**Issue by WindStill** [Zy143L/wskey#24]
commit c43e4af6591421a3c278c1521d7cb22d236d1fd3 
不打印日志信息了

**Comment by Zy143L** [comment]
有截图吗?我这边测试挺ok啊

**Comment by Zy143L** [comment]
![image](https://user-images.githubusercontent.com/21352718/132097915-e0281938-4149-41e3-b603-c059d486884f.png)

**Comment by WindStill** [comment]
![image](https://user-images.githubusercontent.com/958456/132097957-a5d2fec0-9948-4ec6-ba95-9283bac7222a.png)

**Comment by Zy143L** [comment]
?? 删掉脚本从新拉..

**Comment by WindStill** [comment]
> ?? 删掉脚本从新拉..

就是最新的。下午更新完就这样了。刚才我又重新拉了，还是这样

**Comment by Zy143L** [comment]
哈?稍等我删了试试

**Comment by Zy143L** [comment]
还是没问题啊..

**Comment by Zy143L** [comment]
你去脚本管理那边 看看脚本代码..怎么感觉是网络导致的拉取出错

**Comment by WindStill** [comment]
![image](https://user-images.githubusercontent.com/958456/132098551-29597a5d-5925-4248-8c08-16cff4ed1b40.png)
要解密一下吗？

**Comment by WindStill** [comment]
任务执行好像没问题，过期的ck更新了。就是没有日志输出

**Comment by Zy143L** [comment]
不应该啊..我这边测了几个机子都正常//

**Comment by WindStill** [comment]
跟青龙版本有关系吗？我2.8.4-002

**Comment by Zy143L** [comment]
建议升级一下..

**Comment by WindStill** [comment]
不是说2.9的版本，重启容器会丢任务的嘛

**Comment by Zy143L** [comment]
啊? 没发现啊

**Comment by WindStill** [comment]
![image](https://user-images.githubusercontent.com/958456/132098757-12dcdddc-fb11-461f-9520-142def621ef4.png)
2.9.1 有这个问题。 现在最新的是什么版本了？

**Comment by Zy143L** [comment]
我这边2.9.1暂时没发现这个问题...

**Comment by WindStill** [comment]
果然是青龙版本的问题，升级到最新就好了
