### ISSUE TITLE
请问可否添加已禁用的JD_COOKIE，如果WSKEY失效就不提醒

### ISSUE THREAD

**Issue by fidcz** [Zy143L/wskey#240]
如题，有时候大部分WSKEY炸了，但是暂时没空去重新获取。就会一直重复提醒。用了COOKIE失效通知时自动跑WSKEY的，然后一个小时就好一百多条消息

**Comment by Zy143L** [comment]
主要问题是 wskey有很高的误报率 所以说 建议手动禁用对应的JD_WSCK变量

**Comment by fidcz** [comment]
比如第一次wskey更新失败，默认会禁用jd_cookie并且提醒一次。可否添加一个变量开关，用户自己设置后就只会在失效禁用的时候提醒一次
config:
```
export 不重复提醒="true"
```
wskey.py
```
if wskey过期 or 更新wskey失败:
    if 不重复提醒 and jd_cookie已禁用:
        return/continue
    # 开了"不重复提醒"，只会在第一次wskey失效禁用时提醒
    # 如果wskey有效，会自动启用jd_cookie
    禁用JD_COOKIE()
    通知()
```

**Comment by Zy143L** [comment]
自己动手 丰衣足食 短期内不会更新这样子的功能

**Comment by fidcz** [comment]
> 自己动手 丰衣足食 短期内不会更新这样子的功能

好的，谢谢大佬回复
