### ISSUE TITLE
大佬有没有遇到wskey是wskey=...;pin_hash=....这个种格式的

### ISSUE THREAD

**Issue by lvzhaoxing** [Zy143L/wskey#245]
User-Agent: JD4iPhone/168221%20(iPhone;%20iOS;%20Scale/2.00)

抓出来的包，app的ck都是这种类型。
wskey=...;pin_hash=....

通过现在的代码来转换，都是转换出 fake_xxxx 的ck。

**Comment by Zy143L** [comment]
按照格式写..pin=xxx;wskey=xx
pin_hash不用写 pin就是jd的id

**Comment by lvzhaoxing** [comment]
可以了，谢谢大佬
