### ISSUE TITLE
今天突然就转换不了，求help，显示成功但是其实没成功而且不会启用

### ISSUE THREAD

**Issue by MinanaYaa** [Zy143L/wskey#247]
pt_pin=jd_vTunWuPCXEOr;检索成功

jd_vTunWuPCXEOr;状态失效

pt_pin=jd_vTunWuPCXEOr;WsKey状态正常

wskey转换成功

账号启用失败

**Comment by MinanaYaa** [comment]
貌似把cookie调到第一个就能成功了，也不知道是什么神奇的问题

**Comment by Zy143L** [comment]
检查cookie是否出现重复

**Comment by xukf2000** [comment]
还真是，4个账号，每次都是在最前面的成功，上下三个失败，调下位置，又是第一个启用成功

**Comment by Zy143L** [comment]
可以尝试删掉所有cookie 由程序添加
