### ISSUE TITLE
云端参数解析失败

### ISSUE THREAD

**Issue by yemingjkl** [Zy143L/wskey#249]
是服务器宕机了吗

**Comment by Zy143L** [comment]
没有吧

**Comment by Zy143L** [comment]
这边看后台一切正常诶

**Comment by yemingjkl** [comment]
那云端参数解析失败是什么原因呢

**Comment by Zy143L** [comment]
尝试重新执行一下看看  如果还是提示这个 开debug模式截图给我

**Comment by yemingjkl** [comment]
![image](https://user-images.githubusercontent.com/57450589/192138402-0d7535ec-8db4-49f1-ad8a-52d4c43693e9.png)重试了很多次，仍然显示解析失败

**Comment by Zy143L** [comment]
你..是不是用了什么 360路由器啊

**Comment by yemingjkl** [comment]
主路由确实是360路由器，但是我的跑青龙的设备走的旁路由openwrt，之前一直没啥问题，是路由器的原因吗

**Comment by Zy143L** [comment]
路由器劫持了http访问流量 重定向到360的安全页面了

**Comment by yemingjkl** [comment]
OK，把所有360功能关闭之后就好了，我也是没想到360路由器还这么恶心，等京东云的京豆挂满两年刷机

**Comment by Zy143L** [comment]
关爱自身网络安全..先扔掉360设备
