### ISSUE TITLE
提示wskey转换接口出错

### ISSUE THREAD

**Issue by jiangyue999** [Zy143L/wskey#25]
![图片](https://user-images.githubusercontent.com/89628481/132099000-e881257b-af4a-47b8-9f58-7203a12f3144.png)
今天上午还能正常转换，下午就遇到这个问题了

**Comment by Zy143L** [comment]
IP被京东风控了 建议等等 或者换个ip

**Comment by jiangyue999** [comment]
我设置了一小时执行一次，请问是因为我请求次数太多了被风控吗？

**Comment by Zy143L** [comment]
可能是吧...后续推出一个不校验的版本吧 可以自由点
