### ISSUE TITLE
今天频繁出这个

### ISSUE THREAD

**Issue by sevensevenmi** [Zy143L/wskey#252]
xxxxxxx ;检索成功
Traceback (most recent call last):
  File "/ql/data/scripts/Zy143L_wskey_main/wskey.py", line 593, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "/ql/data/scripts/Zy143L_wskey_main/wskey.py", line 293, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by liu269569205** [comment]
同你

**Comment by Zy143L** [comment]
已复现, 在修了 预计晚上

**Comment by liu269569205** [comment]
改了一下源码 可以
        except Exception as err:  # 异常捕捉
            logger.debug(str(err))  # 调试日志输出
            logger.info("JD接口错误 请重试或者更换IP")  # 标准日志输出
            return False  # 返回 Bool类型 False
        else:  # 判断分支
            if res.status_code == 200:  # 判断 JD_API 接口是否为 200 [HTTP_OK]
                try:
                    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
                    if code == 0:  # 判断 code值
                       logger.info(str(pin) + ";状态正常\n")  # 标准日志输出
                       return True  # 返回 Bool类型 True
                    else:  # 判断分支
                       logger.info(str(pin) + ";状态失效\n")
                       return False  # 返回 Bool类型 False
                except Exception as err:  # 异常捕捉
                   logger.info(str(pin) + ";状态失效\n")
                   return False  # 返回 Bool类型 False
            else:  # 判断分支
                logger.info("JD接口错误码: " + str(res.status_code))  # 标注日志输出

**Comment by sevensevenmi** [comment]
> 改了一下源码 可以 原因是 检查ck有效的api返回的是html，json无法解析报错 jd改api了，有效的ck是json格式，无效的是html
是的 我也 获取用户信息那个 变了

**Comment by Zy143L** [comment]
已修复
