### ISSUE TITLE
wskey任务会被自动禁用，是正常情况吗

### ISSUE THREAD

**Issue by yuhouyanran** [Zy143L/wskey#253]
> 检查你其他脚本..wskey脚本不会禁用本身

![image](https://user-images.githubusercontent.com/70701665/198098136-4a3d4a23-75a8-4425-a7c3-ec9fd2cf97bd.png)
![image](https://user-images.githubusercontent.com/70701665/198098264-5e6b16a6-cce4-49ae-a500-c8c1b79876ab.png)
我这里是这样的，有啥问题没

**Comment by Zy143L** [comment]
检查你其他脚本..wskey脚本不会禁用本身

**Comment by yuhouyanran** [comment]
> 检查你其他脚本..wskey脚本不会禁用本身

是因为 WSKEY_SLEEP 这个变量的原因吗

**Comment by Zy143L** [comment]
不是..这个禁用是其他脚本做的 你可以看看你有没有装一些什么 重复脚本禁用 这些的js脚本
wskey_sleep是账号间隔休眠

**Comment by yuhouyanran** [comment]
> 不是..这个禁用是其他脚本做的 你可以看看你有没有装一些什么 重复脚本禁用 这些的js脚本 wskey_sleep是账号间隔休眠

现在里面就运行了一个yyds的库的脚本，除了刷京豆的这个我其他没有运行其他东西了，我试试控制变量法把所有任务全都删除掉只留下wskey这一个任务看看他会不会还是会被禁用，哈哈哈我真是个天才

**Comment by Zy143L** [comment]
yyds里面有一个内置的wskey转换 去看那个禁用重复任务的那个脚本

**Comment by yuhouyanran** [comment]
> yyds里面有一个内置的wskey转换 去看那个禁用重复任务的那个脚本

好的

**Comment by yuhouyanran** [comment]
> yyds里面有一个内置的wskey转换 去看那个禁用重复任务的那个脚本

哦我搜了一下果然有两个wskey任务，我应该把yyds的那个删除吗

**Comment by Zy143L** [comment]
嗯

**Comment by yuhouyanran** [comment]
> 嗯

好的谢谢大佬花时间解答了，给你拜个早年新年快乐哈哈哈
