### ISSUE TITLE
能强制更新ck吗？保证所有ck有效期差不多。

### ISSUE THREAD

**Issue by hdstar2009** [Zy143L/wskey#255]
刚开始用wskey没几天，不知道有没有这样的功能。
现在发现更新时如果ck有效就不会更新，那么多个ck的有效期不一致，只能每个小时运行wskey一次才能保证ck失效后近快更新为有效？频繁运行wskey担心频繁访问接口导致黑，因为我看issue里面有黑到访问不了接口的例子。

**Comment by Zy143L** [comment]
变量名: WSKEY_DISCHECK 参数: 任意(str)

**Comment by hdstar2009** [comment]
谢谢，原来那个参数是这个意思，哈，之前没理解。

export WSKEY_DISCHECK="true" # 不管是否有效，全部强制更新
