### ISSUE TITLE
更新最新版运行出错

### ISSUE THREAD

**Issue by hdstar2009** [Zy143L/wskey#257]
--------------------

5700端口检查通过
'twoFactorSecret'
Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "GET /api/user HTTP/1.1" 200 None
Starting new HTTP connection (1): 127.0.0.1:5700
http://127.0.0.1:5700 "GET /api/envs HTTP/1.1" 200 None
使用 id 键值
Starting new HTTPS connection (1): api.momoe.ml:443
https://api.momoe.ml:443 "GET / HTTP/1.1" 200 12
HTTPS Server Check OK
--------------------

Starting new HTTPS connection (1): api.momoe.ml:443
https://api.momoe.ml:443 "GET /api/check_api HTTP/1.1" 200 636
当前脚本版本: 21031
--------------------

http://127.0.0.1:5700 "GET /api/envs HTTP/1.1" 200 None
pt_pin=jd_51e4f0dd2ee;检索成功

jd_51e4f0dd2ee;未到期，13时32分后更新

pt_pin=jd_51e4f0dd2ee;账号有效
http://127.0.0.1:5700 "PUT /api/envs/enable HTTP/1.1" 200 12

账号启用
--------------------

--------------------

暂停0秒

pt_pin=16320784m;检索成功

16320784m;未到期，13时31分后更新

pt_pin=16320784m;账号有效
http://127.0.0.1:5700 "PUT /api/envs/enable HTTP/1.1" 200 12

账号启用
--------------------

然后不知道为什么所有的wskey生成的appck都失效了，按理说这些appck也不会同时失效而且之前2-3小时还更新过

**Comment by Zy143L** [comment]
你的wskey写了吗

**Comment by Zy143L** [comment]
如果环境变量有JD_WSCK 建议重启下容器

**Comment by hdstar2009** [comment]
然后我发现用互助研究院的ckck3脚本会识别到所有wskey之前运行过的appck都是失效的并更新为有效的。
反馈看看会是什么问题。
