### ISSUE TITLE
转换出CK失效过快

### ISSUE THREAD

**Issue by ROOOCCCK** [Zy143L/wskey#258]
转换的CK格式是pt_key=app_openAAJjY...先有时候一天就是后半天就失效了，想问下大佬有办法设置CK失效自动转换吗，或者推荐怎样设置，现在定时任务调的每天早上6点多

**Comment by Xaple** [comment]
确实 现在一天就失效

**Comment by Zy143L** [comment]
1小时检查一次

**Comment by Zy143L** [comment]
注意切换ip
