### ISSUE TITLE
云端地址失效

### ISSUE THREAD

**Issue by jiangwenjun520** [Zy143L/wskey#262]
云端地址失效. 请联系作者或者检查网络.   基本都挂掉了

**Comment by jiangwenjun520** [comment]
有时就云端链接失败

**Comment by Zy143L** [comment]
api服务器位于香港地区 偶发阻断..也正常

**Comment by jiangwenjun520** [comment]
我还以为是你作者这边禁用了！那么如果使用外网转换应该没什么问题呗

&nbsp;


Emp.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月6日(星期一) 下午2:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Zy143L/wskey] 云端地址失效 (Issue #262)





 
api服务器位于香港地区 偶发阻断..也正常
