### ISSUE TITLE
wskey转换的建议间隔是多少？

### ISSUE THREAD

**Issue by Sharplee** [Zy143L/wskey#264]
大佬，增加wskey转换的定时任务，在执行间隔的cron表达式建议写多久一次？一天2次算频率高么？

**Comment by Sharplee** [comment]
补充再问一下，和WSKEY_UPDATE_HOUR 变量设定之间是什么关系？

**Comment by atomshadows** [comment]
不算，我设置每小时更新一次都常常有脚本提示过期

**Comment by Zy143L** [comment]
这个取决于你的号的风控情况 有些号过期频繁 wskey就得频繁转换
