### ISSUE TITLE
云端地址失效. 请联系作者或者检查网络.

### ISSUE THREAD

**Issue by sevensevenmi** [Zy143L/wskey#267]
## 开始执行... 2023-03-30 10:13:46

--------------------

5700端口检查通过
使用 id 键值

云端地址全部失效, 请检查网络!
WSKEY转换

云端地址失效. 请联系作者或者检查网络.

**Comment by Zy143L** [comment]
服务器故障 稍等片刻

**Comment by sevensevenmi** [comment]
> 服务器故障 稍等片刻

搜戴斯乃

**Comment by Zy143L** [comment]
已修复

**Comment by Zy143L** [comment]
又寄了..我去看看

**Comment by sevensevenmi** [comment]
> 又寄了..我去看看

5700端口检查通过
使用 id 键值
CloudFlare Server Check OK
--------------------

云端参数解析失败

**Comment by sevensevenmi** [comment]
辛苦 辛苦

**Comment by Zy143L** [comment]
你再看看

**Comment by sevensevenmi** [comment]
> 你再看看

可以了
