### ISSUE TITLE
云端地址全部失效, 请检查网络!

### ISSUE THREAD

**Issue by ghehikaru** [Zy143L/wskey#269]
5700端口检查通过
使用 id 键值

云端地址全部失效, 请检查网络!
WSKEY转换

云端地址失效. 请联系作者或者检查网络.

**Comment by Zy143L** [comment]
在修

**Comment by jcjc59461** [comment]
他娘的，我5点多闲的蛋疼就开始搞了一波magisk模块青龙的依赖，然后一直就是这个，还以为是我的问题

**Comment by kettly1260** [comment]
这个不是用的自己的服务器吗？为什么需要云端转换啊

**Comment by Zy143L** [comment]
> 这个不是用的自己的服务器吗？为什么需要云端转换啊

因为加密参数是由服务器生成的

**Comment by ghehikaru** [comment]
> 在修

收到

**Comment by kettly1260** [comment]
> > 这个不是用的自己的服务器吗？为什么需要云端转换啊
> 
> 因为加密参数是由服务器生成的

如果加密也可以自己处理是不是就没有服务器的压力了

**Comment by Zy143L** [comment]
半小时后恢复服务

**Comment by shenmadouyaowen** [comment]
大佬靠谱

**Comment by Zy143L** [comment]
全部修复了
