### ISSUE TITLE
云端地址报错了

### ISSUE THREAD

**Issue by cy920820** [Zy143L/wskey#272]
![image](https://user-images.githubusercontent.com/21211512/236362059-92529139-5727-4449-9adc-d2cdefd8069b.png)

**Comment by nQrChao** [comment]
BBQ

**Comment by sydaint** [comment]
作者答了，地址迁移到6月恢复

**Comment by jjjyyyllll** [comment]
> > 作者答了，地址迁移到6月恢复
> 
> 是6日..不是6月..你这一下给我拉了一个月啊

日是日 月是月 他要吓退骰子
