### ISSUE TITLE
似乎又失效了？

### ISSUE THREAD

**Issue by MilesPoupart** [Zy143L/wskey#275]
首先感谢dalao提供的项目！今天开始又提示云端地址失效了，想问下是又有问题还是请求太频繁被ban了，谢谢！
![Screenshot_20230525_232123_org telegram messenger](https://github.com/Zy143L/wskey/assets/32707318/1672d790-4fc9-4a31-b000-c13d56f78b17)

**Comment by 5jwoj** [comment]
我昨天一天都是这样。。

**Comment by MilesPoupart** [comment]
似乎又正常了

**Comment by 5jwoj** [comment]
确实恢复了

**Comment by MilesPoupart** [comment]
好像又不行了
![image](https://github.com/Zy143L/wskey/assets/32707318/8bb73aee-89e2-4ee2-80dd-c0aa34c4b3de)

**Comment by Zy143L** [comment]
HK的机子 我切个服务器吧..
