### ISSUE TITLE
不知道为什么出错了

### ISSUE THREAD

**Issue by lijiusong** [Zy143L/wskey#276]
Traceback (most recent call last):
  File "/ql/scripts/sign_wskey/wskey.py", line 577, in <module>
    update()  # 调用方法 [update]
  File "/ql/scripts/sign_wskey/wskey.py", line 383, in update
    up_ver = int(cloud_arg['update'])  # 云端参数取值 [int]
KeyError: 'update'

**Comment by shishixiu** [comment]
同

**Comment by shishixiu** [comment]
昨天15：50还正常，16：之后都报错

**Comment by lijiusong** [comment]
是同样的错误吗

**Comment by lijiusong** [comment]
好像看代码，云端返回的参数中只有{"code":200}这么个信息，其他都没有了，原本里面应该是一组信息，存在update这个键的

**Comment by Zy143L** [comment]
2023年5月27日09:47:56 测试均一切正常

**Comment by lijiusong** [comment]
那可能是我青龙的问题？

**Comment by Zy143L** [comment]
> 那可能是我青龙的问题？

你现在还是不能使用吗

**Comment by lijiusong** [comment]
是的，出现以下报错

Traceback (most recent call last):
File "/ql/scripts/sign_wskey/wskey.py", line 577, in
update() # 调用方法 [update]
File "/ql/scripts/sign_wskey/wskey.py", line 383, in update
up_ver = int(cloud_arg['update']) # 云端参数取值 [int]
KeyError: 'update'

**Comment by Zy143L** [comment]
> 是的，出现以下报错
> 
> Traceback (most recent call last): File "/ql/scripts/sign_wskey/wskey.py", line 577, in update() # 调用方法 [update] File "/ql/scripts/sign_wskey/wskey.py", line 383, in update up_ver = int(cloud_arg['update']) # 云端参数取值 [int] KeyError: 'update'

尝试重启面板后重新执行 如果还是报错 请打开Debug模式(脚本-编辑-debug=1再执行)

**Comment by lijiusong** [comment]
家我VX   18267880783   我给你链接和密码，你直接进去看阔以吗

**Comment by Zy143L** [comment]
直接在github上发送截图即可

**Comment by lijiusong** [comment]
![image](https://github.com/Zy143L/wskey/assets/42486196/26f61bde-b897-4e86-97cd-a133b494e256)
突然好了

**Comment by Zy143L** [comment]
可能是出现服务商缓存了...请不要在公开网站发布有关您的任何个人信息

**Comment by lijiusong** [comment]
没有啊，这个就我自己用的，都是一群认识的朋友挂上面

**Comment by Zy143L** [comment]
> 没有啊，这个就我自己用的，都是一群认识的朋友挂上面

指的是你之前发送的联系方式 等 我已经删除了

**Comment by lijiusong** [comment]
蟹蟹
