### ISSUE TITLE
大佬，能否开源下，或者出一个接口？

### ISSUE THREAD

**Issue by xx668888** [Zy143L/wskey#28]
没用ql，可以加个接口 返回 ptkey嘛？ 或者开源下脚本，我自己改下也行，谢谢了

**Comment by Zy143L** [comment]
这个脚本已经够开源了...如果自己没法解压缩
那就等后面  我会出单独的软件

**Comment by xx668888** [comment]
有个 master/sign 接口  是你的嘛  我1分钟内 请求的 获取的sign 都是一样的，然后 转换 出来得 pt_key 就只有一个能用的
