### ISSUE TITLE
在部署青龙的时候没有开启双重验证,最近开启了双重验证后,青龙上不去了

### ISSUE THREAD

**Issue by QiWu666** [Zy143L/wskey#280]
![Screenshot_2023-06-16-20-48-19-077_com android chrome](https://github.com/Zy143L/wskey/assets/46865888/8bc723d6-ba42-4386-810d-f2a0b3be3b69)
不知道如何看日志

**Comment by Zy143L** [comment]
你要是纯内网就把2FA关了吧

**Comment by QiWu666** [comment]
最近莫名其妙收到登录成功的日志，已经好几次了，没有开防火墙，怕是公网ip泄露了，跑着群晖

**Comment by QiWu666** [comment]
不是wskey更新的时候出现的，我也很迷，就开了验证

**Comment by Zy143L** [comment]
按理来说目前2FA参数是没问题的啊 难道青龙改配置了 ?

**Comment by Zy143L** [comment]
未复现成功..

**Comment by QiWu666** [comment]
如何查看log，开了双重通知就是显示青龙登录失败
