### ISSUE TITLE
iOS上获取的wskey转换的时候都是失败的

### ISSUE THREAD

**Issue by jarryyen** [Zy143L/wskey#284]
青龙版本 2.15.17
wskey 版本是最新版本 11.8.0
iOS从steam中抓到的api.xx.xx.com 这个接口中的含有wskey在转换时提示失败

京东app为12.0.4

谢谢

**Comment by Zy143L** [comment]
steam??
同时很抱歉 无iOS设备测试

**Comment by jarryyen** [comment]
> steam??
> 同时很抱歉 无iOS设备测试

stream 抱歉 , 少敲了一个r.

非常感谢,目前iOS获取到的wskey转换是失败的. 暂时只能通过获取cookie暂时使用

再次对您表示感谢,谢谢!

**Comment by Zy143L** [comment]
有条件的话 建议使用安卓平台

**Comment by jarryyen** [comment]
> 有条件的话 建议使用安卓平台

好的,非常感谢

**Comment by RedShameA** [comment]
同最近ios抓到的wskey没法用了，提示WsKey状态失效

**Comment by Zy143L** [comment]
考虑安卓模拟器试试吧 因为我参数给的都是Android 根据我自己手机抓包走的

**Comment by xt53** [comment]
我现在试着是可以的，查查格式是否正确？

**Comment by AemonCao** [comment]
> 我现在试着是可以的，查查格式是否正确？

iOS现在为什么抓不到wskey了？
请问一下你是怎么抓的呢？

**Comment by doubiboy** [comment]
> 考虑安卓模拟器试试吧 因为我参数给的都是Android 根据我自己手机抓包走的

请问WSKEY有效期过短是jd开始限制了吗

**Comment by JoveYu** [comment]
最近ios抓的wskey,2天就失效了，设备登陆状态也踢下来了，这个是号黑了吗，还是jd开始抓了？
