### ISSUE TITLE
请教大佬，提示wskey错误

### ISSUE THREAD

**Issue by elsenjang** [Zy143L/wskey#287]
![CJZ3U9 {GCOJ{@{1`B_%CF9](https://github.com/Zy143L/wskey/assets/78722277/98a094a5-f4d7-4556-9ad4-bcd8b12404d5)

wskey格式没错。

**Comment by doubiboy** [comment]
我的一直提示云端解析失败 好几天了
![image](https://github.com/Zy143L/wskey/assets/38933955/9ffe9d70-30ef-41f3-834e-2a429b3247ee)

**Comment by Zy143L** [comment]
晚些时间处理 域名没了
