### ISSUE TITLE
能否延迟每个ck之间的时间间隔或者让用户自定义时间

### ISSUE THREAD

**Issue by lxr760** [Zy143L/wskey#290]
最近京东又升级风控了，大概转换5个ck以后就会ip封控。能否每转5个以后就等一会，比如5分钟  10分钟这样。等10秒还是不够

![image](https://github.com/Zy143L/wskey/assets/8476457/52ab9b74-1d23-4765-ab17-02841e118f3b)

**Comment by Zy143L** [comment]
看自定义变量..

**Comment by lxr760** [comment]
> 看自定义变量..

变量名: WSKEY_SLEEP 参数: 整数(int)
# 设置 WSKEY_SLEEP 可自定义间隔时间


请问是这个参数吗        这里的时间单位是？

**Comment by Zy143L** [comment]
秒

**Comment by syd1989** [comment]
设置 WSKEY_SLEEP 了 为 20秒，可是，脚本运行还是 默认的10秒间隔，，，，，，，

**Comment by Zy143L** [comment]
你确定你给的参数正确么 实测无问题

**Comment by jerrie610** [comment]
> > 看自定义变量..
> 
> 变量名: WSKEY_SLEEP 参数: 整数(int)
> 
> # 设置 WSKEY_SLEEP 可自定义间隔时间
> 请问是这个参数吗 这里的时间单位是？

这个变量在哪里设置
