### ISSUE TITLE
跪求大佬更新，这个问题"疑似IP风控等问题 默认为失效"已经越来越严重了，等待很长时间也不行

### ISSUE THREAD

**Issue by xfchu1988** [Zy143L/wskey#292]

**Comment by lijiusong** [comment]
我也是这个问题，跪求大佬更新

**Comment by Zy143L** [comment]
随后排查一下

**Comment by lxr760** [comment]
大概转换到10个账号以后就会开始被风控       间隔时间调再长也没用    请大佬研究研究   谢谢

**Comment by jerrie610** [comment]
能解决不？

**Comment by lijiusong** [comment]
可以自己改代码走代理就行了或者直接用6dylan6_jdpro/jd_wsck.py这个脚本，你得挂第三方代理

**Comment by lxr760** [comment]
> 可以自己改代码走代理就行了或者直接用6dylan6_jdpro/jd_wsck.py这个脚本，你得挂第三方代理

挂代理就能突破10个账号被封控的限制？

**Comment by lijiusong** [comment]
每个账号的IP代理都错开就行了

**Comment by jerrie610** [comment]
> 每个账号的IP代理都错开就行了

怎么操作啊，大佬

**Comment by lxr760** [comment]
> 可以自己改代码走代理就行了或者直接用6dylan6_jdpro/jd_wsck.py这个脚本，你得挂第三方代理


6dylan6_jdpro/jd_wsck.py这脚本可以啊     不挂代理也能连续转上几十个号   牛*了



蹲个本站大佬的脚本更新

**Comment by lijiusong** [comment]
https://github.com/bak-up/6dylan6/blob/main/jd_wsck.py
可以用这个脚本啊

**Comment by jerrie610** [comment]
> https://github.com/bak-up/6dylan6/blob/main/jd_wsck.py 可以用这个脚本啊

顺便问问，他这个库好用吗？现在有哪些库是好用的

**Comment by xfchu1988** [comment]
再次拜托大佬有空更新一下，现在用修改的代理版，wskey没几天就失效，不懂什么原因!

**Comment by lxr760** [comment]
> 再次拜托大佬有空更新一下，现在用修改的代理版，wskey没几天就失效，不懂什么原因!

现在wsk3天就会失效    跟用哪个库转换貌似没关系   京东风控升级了

**Comment by Zy143L** [comment]
感觉还是你们号码风控问题 我自己的wskey已经很久没出过问题了 更新的话 中秋节会有一次更新

**Comment by lijiusong** [comment]
不行啊，还是有问题，挂代理获取转cookie,没过几天，号全掉光了！！！！

**Comment by qqqm7** [comment]
确实风控更严了，3天必掉，大佬要不要再确定下还有没有解决办法？

**Comment by Zy143L** [comment]
已经更新
