### ISSUE TITLE
WSKEY格式错误, 这两天才出现这样的

### ISSUE THREAD

**Issue by jerrie610** [Zy143L/wskey#293]
5700端口检查通过
使用 id 键值
Eu_HTTPS Server Check OK
--------------------

当前脚本版本: 21212
--------------------

WSKEY格式错误
--------------------

执行完成
--------------------

## 执行结束... 2023-09-22 22:01:41 耗时 0 秒

**Comment by Zy143L** [comment]
重启青龙面板 删掉wkey从新添加

**Comment by Zy143L** [comment]
确定wskey格式没错么?注意末尾分号以及空行什么的

**Comment by jerrie610** [comment]
确定没错，原来都好好的啊，又没去改它

**Comment by Zy143L** [comment]
那不应该出现这个情况啊 检查下系统环境有没有出现wskey重复的

**Comment by Zy143L** [comment]
你可以看我代码检查的很简单
