### ISSUE TITLE
Params参数获取失败

### ISSUE THREAD

**Issue by lxr760** [Zy143L/wskey#294]
5700端口检查通过
使用 id 键值
pt_pin=***;检索成功

不检查账号有效性
--------------------

Params参数获取失败
15 秒后重试，剩余次数：1

Params参数获取失败
pt_pin=***;账号禁用

账号禁用成功
--------------------

所有wsck转换时都出现这个提示

**Comment by Zy143L** [comment]
当时可能服务器不稳定 现在已经没这个问题了
