### ISSUE TITLE
"疑似IP风控等问题 默认为失效"

### ISSUE THREAD

**Issue by a11466** [Zy143L/wskey#296]
你好最近这几天基本号都风控问题请问是为什么？ 有挂代理在跑的每个账号都是不同的代理

**Comment by a11466** [comment]
我测试了一下好像确实是这个不太行 不是账号的原因

**Comment by 5jwoj** [comment]
我今天也是

**Comment by jsdfhasuh** [comment]
不知道是不是算法换了，几个脚本都转换不出来

**Comment by sxx1314** [comment]
全新ip  都会风控  不知道啥问题

**Comment by sxx1314** [comment]
[faker](https://raw.githubusercontent.com/shufflewzc/faker2/main/jd_wsck.py)
这个脚本转换正常，并且是本地sigin，不过不方便改成异地wskey，在宿主系统下修改docker青龙还是你的脚本方便。

**Comment by Zy143L** [comment]
已更新脚本
