### ISSUE TITLE
正常wskey测试返回 WsKey状态失效

### ISSUE THREAD

**Issue by VicenTYC** [Zy143L/wskey#299]

**Comment by ryan016** [comment]
pt_pin=******;检索成功

Traceback (most recent call last):
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 551, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 246, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
KeyError: 'retcode'

**Comment by Zy143L** [comment]
暂未复现成功 请尝试重启容器从新获取网络

**Comment by boshi116** [comment]
一样


pt_pin=;检索成功

Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_jdpro/jd_wskey.py", line 554, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "/ql/data/scripts/6dylan6_jdpro/jd_wskey.py", line 249, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
KeyError: 'retcode'

**Comment by Zy143L** [comment]
尝试开启debug模式再跑一下 我看看日志 @boshi116

**Comment by boshi116** [comment]
青龙 debug模式 没找到相关设置

**Comment by Zy143L** [comment]
> 青龙 debug模式 没找到相关设置

https://github.com/Zy143L/wskey/blob/a1841a63aaddc06836fb9422c6508023f47aff4f/wskey.py#L16

**Comment by boshi116** [comment]
暂停10秒

pt_pin=;检索成功

Starting new HTTPS connection (1): me-api.jd.com:443
https://me-api.jd.com:443 "GET /user_new/info/GetJDUserInfoUnion HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 551, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "/ql/data/scripts/Zy143L_wskey/wskey.py", line 246, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
KeyError: 'retcode'

**Comment by Zy143L** [comment]
尝试删掉对应的jd_cookie直接去更新

**Comment by Zy143L** [comment]
在246行上面增加一行logger.info(res.text)
然后跑一下我看看情况

**Comment by boshi116** [comment]
通过测试发现第6个账号就出错  把出错的账号移到第一的位置  这个账号就可以正常更新  到第六个还是会出错

**Comment by Zy143L** [comment]
你把logger.info(res.text)这个加上 注意对齐
然后跑 报错给我日志

**Comment by boshi116** [comment]
else:
            if res.status_code == 200:  # 判断 JD_API 接口是否为 200 [HTTP_OK]
                    logger.info(res.text)
                   code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
         这样是吧

**Comment by Bigggggggg226** [comment]
Starting new HTTPS connection (1): me-api.jd.com:443

https://me-api.jd.com:443 "GET /user_new/info/GetJDUserInfoUnion HTTP/1.1" 200 None

Traceback (most recent call last):
  File "wskey.py", line 552, in <module>
    if not check_ck(jck):  # bool: False 判定 JD_COOKIE 有效性
  File "wskey.py", line 246, in check_ck
    code = int(json.loads(res.text)['retcode'])  # 使用 Json模块对返回数据取值 int([retcode])
KeyError: 'retcode'
debug和logger的报错
