### ISSUE TITLE
失效快

### ISSUE THREAD

**Issue by dnpl** [Zy143L/wskey#303]
是不是可以限制某些脚本，可以延长CK的有效期，wskey四天基本就掉一次

**Comment by huluohu** [comment]
我用这个转的ck，1天失效。。

**Comment by dnpl** [comment]
> 我用这个转的ck，1天失效。。

我还可以维持3天，三天后基本就失效了

**Comment by Zy143L** [comment]
每个账号对应风控不一样 请主要自己跑的脚本
