### ISSUE TITLE
暂停时长调到多少合适啊

### ISSUE THREAD

**Issue by jcjc59461** [Zy143L/wskey#304]
有19个ck要转换，从最开始的暂停10秒，加到60秒，到后面的120秒，130秒，前15个号在120秒的暂停时，可以稳定更新，唯独后面这4个，加到130秒的间隔都不行，说什么疑似IP风控等问题 默认为失效，我等半小时后去执行转换，ip也没换，间隔更是因为只留了那4个wskey把其他的全禁了变成了10秒。同一个ip是不是一小时只能转15个啊

**Comment by Zy143L** [comment]
建议多开容器 或者增加代理

**Comment by jcjc59461** [comment]
![Screenshot_2024-03-09-16-34-02-472_com quark browser](https://github.com/Zy143L/wskey/assets/75699313/71c5e311-b3f0-4945-a9e1-f691376c8038)
魔怔了，整了个desi指定运行来达到这个效果，差点忘了我是新版青龙

**Comment by Zy143L** [comment]
我还没更新 新版能加这些参数了啊 不错

**Comment by jcjc59461** [comment]
![IMG_20240504_152148](https://github.com/Zy143L/wskey/assets/75699313/111ec60b-2516-4f3c-bf30-7a9cb6fd2193)
最近老出现这个params参数获取失败啊，有时几天都不会有，今天9点多开始转换，连续7-8个号都是这样

**Comment by Zy143L** [comment]
重启下你镜像和网络

**Comment by jcjc59461** [comment]
我的网基本不重启，路由器正常一年都不会重启，我还是重启下青龙面板吧

**Comment by Zy143L** [comment]
参数服务器是HK的 部分地方可能间歇性阻断

**Comment by jcjc59461** [comment]
其实我的网络有ipv6和ipv4,以及常年在路由器上挂着的梯子，服务器在hk按理说应该走梯子啊
