### ISSUE TITLE
转ck间隔问题

### ISSUE THREAD

**Issue by ycyfff** [Zy143L/wskey#32]
我看转wsck几秒钟就把所有的转完了，这样同一时间提交好像对号会有点影响，我所有CK京喜领88红包全火爆了，其他的活动也有黑了，能不能加个变量让第一个转完、替换后，过个几分钟在转下一个号，默认300秒，可以自定义变量。
猜测的是同一时间转码的影响，我也不确定，但还是希望加一下延迟转码

**Comment by a327777892** [comment]
你的猜测没屌用
