### ISSUE TITLE
auth.json 路径问题

### ISSUE THREAD

**Issue by shenmadouyaowen** [Zy143L/wskey#39]
大佬,能否把auth.json的路径加入环境变量,可以自定义呢?

**Comment by Zy143L** [comment]
还有人改auth.json的位置??

**Comment by shenmadouyaowen** [comment]
没有,我把你的脚本在青龙容器外面的服务器使用更新,然后发现跟映射的路径不一样,没事了,我弄了软连接,已经解决,谢谢大佬

**Comment by Zy143L** [comment]
容器外的服务器..需要你自己配置环境变量

**Comment by shenmadouyaowen** [comment]
是的,已经解决了
