### ISSUE TITLE
脚本出错

### ISSUE THREAD

**Issue by hejun041** [Zy143L/wskey#45]
![image](https://user-images.githubusercontent.com/16474051/132467869-8e09f981-b89c-4bfe-bd9b-9023bd14c492.png)
这个账号好像一直都有点问题

**Comment by Zy143L** [comment]
删掉这个账号, 重新添加WSKEY

**Comment by Tony-N2** [comment]
我也出现这个问题， 其中一个号莫名其妙就好了。
后面加的号也都这样， 删除jd_wsky变量重新加也没变化
