### ISSUE TITLE
JD-COOKIE过期后，手动运行wskey虽然能检测到失效，但是不能更新。

### ISSUE THREAD

**Issue by lukemin** [Zy143L/wskey#48]
JD-COOKIE过期后，手动运行wskey虽然能检测到失效，但是不能更新。必须删除现有JD-COOKIE后再运行wskey，检测到没有JD-COOKIE，就会转换添加出没有过期的JD-COOKIE。

**Comment by mjyhj** [comment]
没遇到这个问题，一直正常

**Comment by Zy143L** [comment]
没发现这个问题..逻辑上是
拿JD_COOKIE去检测有效性 失效就返回false 然后更新 (替换已有变量 不存在的话就添加新的
不会说不能更新吧?
检查下你的用户名里面有没有中文
