### ISSUE TITLE
求作者大哥，针对失效更改的及时性做一点修改

### ISSUE THREAD

**Issue by jiangwenjun520** [Zy143L/wskey#49]
不管cookie 是否过期。。一般cookie有效期一天内确定没问题。。那么可否每天我们就定时运行一次并直接修改cookie。这样就减少了运行次数，还失效率降到零

**Comment by mjyhj** [comment]
> 不管cookie 是否过期。。一般cookie有效期一天内确定没问题。。那么可否每天我们就定时运行一次并直接修改cookie。这样就减少了运行次数，还失效率降到零

可以添加变量名: QL_WSCK 参数: 任意(str值)	  		 # 设置QL_WSCK变量后 不检查有效性 直接更新
自己设置每天运行一次不就行，直接强制更新
