### ISSUE TITLE
能否添加失效通知的时候自动调用task wskey

### ISSUE THREAD

**Issue by 21ki** [Zy143L/wskey#50]
![image](https://user-images.githubusercontent.com/24515576/132933303-034edaa7-0b9b-4e3c-ad6d-5adae6e4711a.png)
类似这样通知的时候自动更新一次并启用
我修改成这样还是会被禁用
![image](https://user-images.githubusercontent.com/24515576/132933333-cbee6f0f-d5d2-4224-8ab5-c61561ebd66b.png)

**Comment by Zy143L** [comment]
建议设置QL_WSCK变量 不检查有效性 直接12小时替换一次

**Comment by hong0980** [comment]
`		if (text.indexOf("cookie已失效") != -1 || desp.indexOf("重新登录获取") != -1 || text == "Ninja 运行通知") {

			if (Notify_CKTask) {
				console.log("触发CK脚本，开始执行....");
				Notify_CKTask = "task " + Notify_CKTask + " now";
				await exec(Notify_CKTask, function (error, stdout, stderr) {
					console.log(error, stdout, stderr)
				});
			}
			if (Notify_NoCKFalse == "true" && text != "Ninja 运行通知") {
				return;
			}
		}`
ccwav 的sendNotify.js里的，只要添加环境变量Notify_CKTask就行能运修改，就是运行wskey后ck变量不会重新读取，N个ck失效就运行N次。
