### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by picossin** [Zy143L/wskey#53]
转换失败，提示如下
日志-wskey转换
## 开始执行... 2021-09-12 09:01:54

--------------------

5700端口检查通过

当前脚本版本: 905
--------------------

Verification passed
--------------------

pt_pin=jd_wfzOgEhwLKgq;检索成功

不检查账号有效性
--------------------

WSKEY转换接口出错, 请稍后尝试, 脚本退出

## 执行结束... 2021-09-12 09:01:57 耗时 3 秒

**Comment by Tony-N2** [comment]
把jd_ck变量删除， wsck会自动转换并添加，我刚弄好

**Comment by Zy143L** [comment]
字面意思 接口出错 接口都是JD的 建议等等再用

**Comment by BIGBbox** [comment]
我青龙面板填单个cookie就签到脚本能显示一个脚本生效,填多个后就使用签到脚本就显示0个账号,就用不了,裂开啊

**Comment by sevensevenmi** [comment]
我这2天也遇到这个问题 很频繁 
pt_pin=jd_4*******;检索成功


JD接口错误! 
脚本退出

**Comment by lukemin** [comment]
青龙2.9.2-002
JD_WSCK 也是正确的。转换错误不是所有的都错误，中间出的错，下次有成功了。

**Comment by Zy143L** [comment]
> 青龙2.9.2-002
> JD_WSCK 也是正确的。转换错误不是所有的都错误，中间出的错，下次又成功了。

已经更新了 等后续报错看看日志
