### ISSUE TITLE
我都把号删了为什么还在那转换？是哪里有缓存吗？

### ISSUE THREAD

**Issue by 895450603** [Zy143L/wskey#55]

**Comment by Zy143L** [comment]
建议检查环境变量 config这些

**Comment by 895450603** [comment]
> 建议检查环境变量 config这些

重启了一下容器正常了，辛苦大佬

**Comment by 895450603** [comment]
> 建议检查环境变量 config这些

大佬，首次添加是一定要JD_WSCK吗，我把原来变量删掉以后直接加QL_WSCK提示我没有JD_WSCK变量

**Comment by 895450603** [comment]
> 建议检查环境变量 config这些

大佬，首次添加是一定要JD_WSCK吗，我把原来变量删掉以后直接把wskey填进QL_WSCK提示我没有JD_WSCK变量

**Comment by Zy143L** [comment]
没有JD_WSCK怎么转换呢
