### ISSUE TITLE
青龙登录失败, 请检查面板状态!

### ISSUE THREAD

**Issue by vSolo** [Zy143L/wskey#57]
大佬，发现在半夜和早上的时候日志里面就会是【青龙登录失败, `请检查面板状态!】，白天基本都是正常的。搜索了一下有人说是nanja设置了3天过期，我安装了不过没有使用nanja。日期里面也是expiration，没有3天设置，请有时间帮忙看看哈，感谢大佬。
青龙版本 2.9.1
## auth.ts文件找了一下是这样的
const expiration = twoFactorActived ? 30 : 3;
let token = jwt.sign({ data }, config.secret as any, {
expiresIn: 60 * 60 * 24 * expiration,
algorithm: 'HS384',

## wskey_wskey日志如下：

![image](https://user-images.githubusercontent.com/9264222/133345793-23b58e11-8abd-4424-a1c6-7d367cf938d7.png)

**Comment by Zy143L** [comment]
看auth.json而不是auth.ts
