### ISSUE TITLE
一直检索失败

### ISSUE THREAD

**Issue by wabcwell** [Zy143L/wskey#58]
5700端口检查通过

当前脚本版本: 915
--------------------

Verification passed
--------------------

pt_pt_pin=jd_7fc4cd8e3c62f;检索失败

wskey未生成pt_key

pt_pin=jd_7fc4cd8e3c62fwskey状态失效

执行完成

**Comment by Zy143L** [comment]
后面已经写了，wskey状态失效

**Comment by wabcwell** [comment]
> 后面已经写了，wskey状态失效

可是我抓包出来的wskey就是这个啊，我刚刚又去确认了一下 wskey还是这个

**Comment by Zy143L** [comment]
检查分号问题..记住从pin=xxx;wskey=xxx;
分号结束
