### ISSUE TITLE
915的版本还是自动转换失败

### ISSUE THREAD

**Issue by qq2519157** [Zy143L/wskey#59]
![image](https://user-images.githubusercontent.com/24367208/133531038-ec7b64b0-4142-4553-9dab-92cec68122e2.png)

**Comment by Zy143L** [comment]
916版本进行了处理 请更新

**Comment by Zy143L** [comment]
现在这个版本还有问题吗?

**Comment by qq2519157** [comment]
![image](https://user-images.githubusercontent.com/24367208/133599767-ea336e95-df95-4a1d-8d8c-8b433f2447f2.png)
 
还是有问题

**Comment by Zy143L** [comment]
更新到916版本

**Comment by Zy143L** [comment]
从新更新了 2021年9月16日18:59:56 麻烦再更一下

**Comment by qq2519157** [comment]
更新了，明早看下结果

**Comment by qq2519157** [comment]
昨天更新后是这个报错
![image](https://user-images.githubusercontent.com/24367208/133704870-c8ee981f-d4fa-4e47-b48f-0182c8f01afa.png)

**Comment by Zy143L** [comment]
改一下定时任务的时间 cron的 15改成其他数字

**Comment by qq2519157** [comment]
调整分钟后可以了
