### ISSUE TITLE
等v4头发白了

### ISSUE THREAD

**Issue by yangzhicong** [Zy143L/wskey#64]
老大，我v4都等头发都白了，还是没支持😰

**Comment by hong0980** [comment]
你可用noobx/jd:gitee这个v3的版本带wskey.js。但也可提取出来用，但是好像绑定sendNotify.js用的，必须用他的sendNotify.js才能运行。具体　https://gitee.com/dockere/jd-base/issues/I489KT

**Comment by hong0980** [comment]
你可用noobx/jd:gitee这个v3的版本带wskey.js。但也可提取出来用，但是好像绑定sendNotify.js用的，必须用他的sendNotify.js才能运行。具体　https://gitee.com/dockere/jd-base/issues/I489KT 但没有这个wskey.py好用。

**Comment by hong0980** [comment]
你可用noobx/jd:gitee这个v3的版本带wskey.js。也可提取出来用v4，我的v4就在运行，这个是绑定sendNotify.js用的，必须用他的sendNotify.js才能运行。具体　https://gitee.com/dockere/jd-base/issues/I489KT，但没有这个wskey.py好用。

**Comment by hong0980** [comment]
你可用noobx/jd:gitee这个v3的版本带wskey.js，也可提取出来用v4。我的v4就在运行，这个是绑定sendNotify.js用的，必须用他的sendNotify.js才能运行。具体　https://gitee.com/dockere/jd-base/issues/I489KT 但没有这个wskey.py好用。

**Comment by yangzhicong** [comment]
我把提取wskey出来后，然后手动创建了一个wskey.json文件，最后运行时日志提示似乎被盗用被盗用，然后脚本结束。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zy143L/wskey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月19日(星期天) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zy143L/wskey] 等v4头发白了 (#64)





 
你可用noobx/jd:gitee这个v3的版本带wskey.js，也可提取出来用v4。我的v4就在运行，这个是绑定sendNotify.js用的，必须用他的sendNotify.js才能运行。具体　https://gitee.com/dockere/jd-base/issues/I489KT 但没有这个wskey.py好用。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hong0980** [comment]
> 我把提取wskey出来后，然后手动创建了一个wskey.json文件，最后运行时日志提示似乎被盗用被盗用，然后脚本结束。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zy143L/wskey" ***@***.***&gt;; 发送时间:&nbsp;2021年9月19日(星期天) 下午3:23 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Zy143L/wskey] 等v4头发白了 (#64) 你可用noobx/jd:gitee这个v3的版本带wskey.js，也可提取出来用v4。我的v4就在运行，这个是绑定sendNotify.js用的，必须用他的sendNotify.js才能运行。具体　https://gitee.com/dockere/jd-base/issues/I489KT 但没有这个wskey.py好用。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
不说还要用他的sendNotify.js，还要安装依赖got tough-cookie，下面是我的diy下的shell脚本，运行wskey.js时sendNotify.js复制过去
	[ "`grep -c wskey $ShellDir/jtask.sh`" = 0 ] && \
	sed -i '/main "$@"/i\if [ "$1" = "wskey" ]; then\n	mv $dir_scripts/sendNotify.js $dir_config/p_sendNotify.js\n	cp -r ${dir_sample}/sendNotify.js ${dir_scripts}\nelse\n	[ -f $dir_config/p_sendNotify.js ] && mv $dir_config/p_sendNotify.js $dir_scripts/sendNotify.js\nfi\n' $ShellDir/{jtask.sh,otask.sh,mtask.sh}
	sed -i 's|tg频道 ：https://t.me/bean_plant|本通知 By：wudongdefeng|' $dir_scripts/sendNotify.js
	[ "`grep -c 'wskey' $list_crontab_user`" -eq "0" ] && \
	sed -i "/重启挂机程序/i # 每12小时定时更新Cookie\n55 11,23 \* \* \* $cmd_jtask wskey\n" $list_crontab_user
	sed -i '/wskey/ s/^#//' $list_crontab_user
	[[ "$(npm ls got -g)" =~ (empty) ]] && cd $dir_scripts && npm i got tough-cookie -g

**Comment by hong0980** [comment]
不说还要用他的sendNotify.js，还要安装依赖got tough-cookie，下面是我的diy下的shell脚本，运行wskey.js时sendNotify.js复制过去
	[ "`grep -c wskey $ShellDir/jtask.sh`" = 0 ] && \
	sed -i '/main "$@"/i\if [ "$1" = "wskey" ]; then\n	mv $dir_scripts/sendNotify.js $dir_config/p_sendNotify.js\n	cp -r ${dir_sample}/sendNotify.js ${dir_scripts}\nelse\n	[ -f $dir_config/p_sendNotify.js ] && mv $dir_config/p_sendNotify.js $dir_scripts/sendNotify.js\nfi\n' $ShellDir/{jtask.sh,otask.sh,mtask.sh}
	sed -i 's|tg频道 ：https://t.me/bean_plant|本通知 By：wudongdefeng|' $dir_scripts/sendNotify.js
	[ "`grep -c 'wskey' $list_crontab_user`" -eq "0" ] && \
	sed -i "/重启挂机程序/i # 每12小时定时更新Cookie\n55 11,23 \* \* \* $cmd_jtask wskey\n" $list_crontab_user
	sed -i '/wskey/ s/^#//' $list_crontab_user
	[[ "$(npm ls got -g)" =~ (empty) ]] && cd $dir_scripts && npm i got tough-cookie -g

**Comment by hong0980** [comment]
不说还要用他的sendNotify.js，还要安装依赖got tough-cookie，下面是我的diy下的shell脚本，运行wskey.js时sendNotify.js复制过去
	[ "`grep -c wskey $ShellDir/jtask.sh`" = 0 ] && \
	sed -i '/main "$@"/i\if [ "$1" = "wskey" ]; then\n	mv $dir_scripts/sendNotify.js $dir_config/p_sendNotify.js\n	cp -r ${dir_sample}/sendNotify.js ${dir_scripts}\nelse\n	[ -f $dir_config/p_sendNotify.js ] && mv $dir_config/p_sendNotify.js $dir_scripts/sendNotify.js\nfi\n' $ShellDir/{jtask.sh,otask.sh,mtask.sh}
	[ "`grep -c 'wskey' $list_crontab_user`" -eq "0" ] && \
	sed -i "/重启挂机程序/i # 每12小时定时更新Cookie\n55 11,23 \* \* \* $cmd_jtask wskey\n" $list_crontab_user
	sed -i '/wskey/ s/^#//' $list_crontab_user
	[[ "$(npm ls got -g)" =~ (empty) ]] && cd $dir_scripts && npm i got tough-cookie -g

**Comment by yyetss** [comment]
> 你可用noobx/jd:gitee这个v3的版本带wskey.js，也可提取出来用v4。我的v4就在运行，这个是绑定sendNotify.js用的，必须用他的sendNotify.js才能运行。具体　https://gitee.com/dockere/jd-base/issues/I489KT 但没有这个wskey.py好用。

运行了一下确实可以用。这个作者稳不稳？
