### ISSUE TITLE
新截取的wskey也提示wskey失效

### ISSUE THREAD

**Issue by wanthigh** [Zy143L/wskey#66]
昨晚我好几个号的wskey都提示失效，然后我重新获取了还是一样的，这是什么情况啊老板

**Comment by wanthigh** [comment]
报的错是signature verification failed

**Comment by Zy143L** [comment]
我脚本里面没开签名错误的输出啊 你这是怎么看到的呢

**Comment by wanthigh** [comment]
> 
> 
> 我脚本里面没开签名错误的输出啊 你这是怎么看到的呢

我断点跟的，res里返回的是这个报错

**Comment by Zy143L** [comment]
极速版和惊喜换接口了 sign换64位的了 这个是京东的接口 用惊喜极速版的wskey转出来是pt_key=fake错误罢了

**Comment by wanthigh** [comment]
> 
> 
> 极速版和惊喜换接口了 sign换64位的了 这个是京东的接口 用惊喜极速版的wskey转出来是pt_key=fake错误罢了

是这样的，很僵硬
