### ISSUE TITLE
关于WSKEY转换的问题

### ISSUE THREAD

**Issue by Zy143L** [Zy143L/wskey#67]
目前京喜，极速版等app已更换接口 wskey接口不通用
只能使用京东主APP抓取的wskey进行转换
后台执行失败的 请修改定时时间

**Comment by wanthigh** [comment]
> 
> 
> 目前京喜，极速版等app已更换接口 wskey接口不通用
> 只能使用京东主APP抓取的wskey进行转换
> 后台执行失败的 请修改定时时间

我提的问题可能就是这个导致的了

**Comment by wanthigh** [comment]
这个会有解决方案出来吗

**Comment by Zy143L** [comment]
> 这个会有解决方案出来吗

等咯
