### ISSUE TITLE
跪求一个可以直接转换的版本

### ISSUE THREAD

**Issue by wanthigh** [Zy143L/wskey#7]
能提供一个不依赖青龙环境，直接调用py可以获取数据的接口吗？老板

**Comment by haohaoget** [comment]
这个我觉得应该也可以的但是要转换需要5个参数，其实你也可以直接在机器上做个网络接口直接调用该脚本可以实现一样的效果

**Comment by wanthigh** [comment]
> 
> 
> 这个我觉得应该也可以的但是要转换需要5个参数，其实你也可以直接在机器上做个网络接口直接调用该脚本可以实现一样的效果
我试了下，是要判断ql环境的

**Comment by HowieHye** [comment]
想办法把源码decode出来 ，然后自己修改

**Comment by Zy143L** [comment]
能解开gzip压缩的都能看懂也能改
gzip都解不开的 我估计你也不会改..v4的话 等后面安排吧

**Comment by wanthigh** [comment]
> 
> 
> 能解开gzip压缩的都能看懂也能改
> gzip都解不开的 我估计你也不会改..v4的话 等后面安排吧

在改了老哥，感谢
