### ISSUE TITLE
JD接口错误!  脚本退出

### ISSUE THREAD

**Issue by 754724554** [Zy143L/wskey#70]
多账号只显示第一个检索成功

**Comment by Zy143L** [comment]
账号轮询检索 逻辑没问题 JD接口错误 代表你网络不好或者IP被京东拉黑了

**Comment by 754724554** [comment]
那可如何是好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月24日(星期五) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zy143L/wskey] JD接口错误!  脚本退出 (#70)





 
账号轮询检索 逻辑没问题 JD接口错误 代表你网络不好或者IP被京东拉黑了

**Comment by Zy143L** [comment]
等一段时间或者换个从新拨号换IP

**Comment by 754724554** [comment]
我重启了路由换了IP也一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月24日(星期五) 中午1:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zy143L/wskey] JD接口错误!  脚本退出 (#70)





 
等一段时间或者换个从新拨号换IP
 
&mdash;

**Comment by Zy143L** [comment]
刚刚试了下 没问题啊

**Comment by 754724554** [comment]
我换了几个wskey试都不行 变量也换QL_WSCK显示WSKEY转换接口出错, 请稍后尝试, 脚本退出



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月24日(星期五) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zy143L/wskey] JD接口错误!  脚本退出 (#70)





 
Reopened #70.
 
&mdash;

**Comment by Zy143L** [comment]
京东极速版 京喜等都不能用 只能用主APP

**Comment by 754724554** [comment]
是用京东app的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月24日(星期五) 下午2:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zy143L/wskey] JD接口错误!  脚本退出 (#70)





 
京东极速版 京喜等都不能用 只能用主APP
 
&mdash;

**Comment by Zy143L** [comment]
![image](https://user-images.githubusercontent.com/21352718/134626926-3c5f7302-dd6d-4023-bb64-cb49a568968c.png)
我这测试真没问题..

**Comment by 754724554** [comment]
我也没搞懂哪里出了问题 难道我这些号都被京东专门封了
