### ISSUE TITLE
WSKEY转换接口出错

### ISSUE THREAD

**Issue by lekibsha** [Zy143L/wskey#71]
pt_pin=555555554;检索失败

wskey未生成pt_key

WSKEY转换接口出错, 请稍后尝试, 脚本退出

 总共5个号，就这个号提示错误

**Comment by lekibsha** [comment]
![图片](https://user-images.githubusercontent.com/77033365/134639202-d5f4b547-15a6-4788-a032-39076aaf5110.png)

**Comment by Zy143L** [comment]
接口出错 那就等等吧
