### ISSUE TITLE
自动执行错误

### ISSUE THREAD

**Issue by cc123687** [Zy143L/wskey#72]
早上自动执行成功，下午就执行失败

`## 开始执行... 2021-09-24 16:20:00

--------------------

5700端口检查通过

当前脚本版本: 916
--------------------

Verification passed
--------------------

Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 422, in <module>
    return_serch = serch_ck(wspin)  # 变量 pt_pin 搜索获取 key eid
  File "Zy143L_wskey_wskey.py", line 307, in serch_ck
    if len(res['data']) == 0:
KeyError: 'data'

## 执行结束... 2021-09-24 16:20:03 耗时 3 秒
`

**Comment by Zy143L** [comment]
尝试重启青龙
