### ISSUE TITLE
问个问题，脚本检测更新频率。

### ISSUE THREAD

**Issue by nethawkhu** [Zy143L/wskey#8]
好像是4小时检测一次 CK，CK不失效就不更新，那如果有极端的情况，刚检测的那时刻CK是有效的，检测完了正好到期失效，那就要等4小时后才能更新了。目前来看 WSKEY 是24小时必然失效的，是否可以设置每天固定的时间进行统一更新，不管过期与否都更新。而其他时间可以和原来一样，是一旦检测到CK失效就自动更新。

**Comment by Zy143L** [comment]
下次一定
