### ISSUE TITLE
青龙2.8.3版本api/user/notification检测token接口无效

### ISSUE THREAD

**Issue by venpong** [Zy143L/wskey#82]
青龙2.8.3版本api/user/notification检测token接口无效，该接口不返回200，导致一直提示重新登陆无法成功转换ck，实际上Token是有效的

**Comment by Zy143L** [comment]
行我换一个

**Comment by Zy143L** [comment]
切换到了/api/apps接口 你看下

**Comment by venpong** [comment]
大佬还是不行,2.8.3好像没有/api/apps这个接口,我输出接口返回结果显示404,我现在把这段代码删了，目前暂时能用。
![image](https://user-images.githubusercontent.com/14030911/136721959-975b964e-816e-42bd-aa35-3dc5669178a3.png)
![image](https://user-images.githubusercontent.com/14030911/136721976-c3df1732-c0fa-4814-9688-f2f1a6a99624.png)
