### ISSUE TITLE
云端参数解析失败

### ISSUE THREAD

**Issue by ljhnchina** [Zy143L/wskey#96]
手动更新没有问题，定时自动更新就会出错，云端参数解析失败

**Comment by Zy143L** [comment]
接口被人撸爆了..导致的问题

**Comment by darkrain88** [comment]
> 
> 
> 接口被人撸爆了..导致的问题

老大， 你的服务器， 是不是宕机了。

**Comment by Zy143L** [comment]
> > 接口被人撸爆了..导致的问题
> 
> 老大， 你的服务器， 是不是宕机了。

看了下 日志 没问题啊 就3次500错误 你更新下程序
