### ISSUE TITLE
新版本遇到失效账号好像就停止了  报这个错

### ISSUE THREAD

**Issue by lihkhy** [Zy143L/wskey#99]
serverJ服务启动
Traceback (most recent call last):
  File "Zy143L_wskey_wskey.py", line 447, in <module>
    send('WsKey转换脚本', text)
  File "/ql/scripts/notify.py", line 270, in send
    serverJ(title=title, content=content)
  File "/ql/scripts/notify.py", line 99, in serverJ
    if response['errno'] == 0:
KeyError: 'errno'

**Comment by darkrain88** [comment]
5700端口检查通过

HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f50214c9c40>: Failed to establish a new connection: [Errno -3] Try again'))
未知错误, 退出脚本!

l新脚本连不上了

**Comment by Zy143L** [comment]
青龙的推送问题..,我尝试try下

**Comment by Zy143L** [comment]
> 5700端口检查通过
> 
> HTTPConnectionPool(host='moe.shizuku.ml', port=8443): Max retries exceeded with url: /check_api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f50214c9c40>: Failed to establish a new connection: [Errno -3] Try again')) 未知错误, 退出脚本!
> 
> l新脚本连不上了

检查你的本地网络问题

**Comment by licky008** [comment]
也出现这样的，网络畅通，更换IP还是不行

**Comment by le2yun** [comment]
我还以为只有我一个人有问题。。原来大家都是

**Comment by Zy143L** [comment]
请更脚本
